### ISSUE TITLE
[Feature Request] Support M1 Mac's GPU

### ISSUE THREAD

**Issue by 0x1FFFFF** [m-bain/whisperX#109]
If I pass in `mps` to device option it will crush. Would be wonderful if M1 GPU can be supported

```
❯ whisperx assets/test.mp3 --device mps --model large-v2 --vad_filter --align_model WAV2VEC2_ASR_LARGE_LV60K_960H --diarize --hf_token token --language en

torchvision is not available - cannot save figures
Performing VAD...
~~ Transcribing VAD chunk: (01:07:46.006 --> 01:07:50.663) ~~
loc("mps_multiply"("(mpsFileLoc): /AppleInternal/Library/BuildRoots/9e200cfa-7d96-11ed-886f-a23c4f261b56/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphUtilities.mm":228:0)): error: input types 'tensor<1x1280x3000xf16>' and 'tensor<1xf32>' are not broadcast compatible
LLVM ERROR: Failed to infer result type(s).
[1]    97334 abort      whisperx assets/test.mp3 --device mps --model large-v2 --vad_filter       en
/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

**Comment by wllbll** [comment]
ye, i got this error too, it seems we need to wait update from pytorch

**Comment by Harith163** [comment]
Hi, I believe PyTorch has support for most of the functions now. Plus it can be run with env arg PYTORCH_ENABLE_MPS_FALLBACK=1 for those functions that aren't supported yet to fall back on the CPU.

I'm running pyannote and other projects with PyTorch compiled with support for mps so this should also be do-able

**Comment by Herb-sh** [comment]
@Harith163 That is correct. Pytorch has implemented ["mps"](https://developer.apple.com/metal/pytorch/)(Metal Performance Shaders) for a at least a year now, Open-AI Whisper supports "mps" as well but faster-whisper used by WhisperX apparently only supports "cpu" and "gpu". 

I myself get "unsupported device mps", here is the error:

`--> 128 self.model = ctranslate2.models.Whisper(
    129     model_path,
    130     device=device,
    131     device_index=device_index,
    132     compute_type=compute_type,
    133     intra_threads=cpu_threads,
    134     inter_threads=num_workers,
    135 )`

For me with Mac M1 "cpu" is extremely slow to the point I have not been able to get e proper transcription.

Any workaround to the issue? I believe this is essential for mac users.

Thanks :)

**Comment by 7k50** [comment]
> @Harith163 That is correct. Pytorch has implemented ["mps"(Metal Performance Shaders)](https://developer.apple.com/metal/pytorch/) for a at least a year now, Open-AI's Whisper supports "mps" as well but faster-whisper used by WhisperX apparently only supports "cpu" and "gpu".
> 
> I myself get "unsupported device mps", here is the error:
> 
> `--> 128 self.model = ctranslate2.models.Whisper( 129 model_path, 130 device=device, 131 device_index=device_index, 132 compute_type=compute_type, 133 intra_threads=cpu_threads, 134 inter_threads=num_workers, 135 )`
> 
> For me with Mac M1 "cpu" is extremely slow to the point I have not been able to get e proper transcription.
> 
> Any workaround to the issue? I believe this is essential for mac users.
> 
> Thanks :)

[Whisper.cpp](https://github.com/ggerganov/whisper.cpp) is fast on Apple Silicon ("Plain C/C++ implementation without dependencies" … "optimized via ARM NEON, Accelerate framework, Metal and Core ML"). However, I believe it only supports very rudimentary diarization currently.

Ideally, WhisperX's solutions for diarization, etc, could be made to work in the fashion of Whisper.cpp.

**Comment by PurpShell** [comment]
> > @Harith163 That is correct. Pytorch has implemented ["mps"(Metal Performance Shaders)](https://developer.apple.com/metal/pytorch/) for a at least a year now, Open-AI's Whisper supports "mps" as well but faster-whisper used by WhisperX apparently only supports "cpu" and "gpu".
> > I myself get "unsupported device mps", here is the error:
> > `--> 128 self.model = ctranslate2.models.Whisper( 129 model_path, 130 device=device, 131 device_index=device_index, 132 compute_type=compute_type, 133 intra_threads=cpu_threads, 134 inter_threads=num_workers, 135 )`
> > For me with Mac M1 "cpu" is extremely slow to the point I have not been able to get e proper transcription.
> > Any workaround to the issue? I believe this is essential for mac users.
> > Thanks :)
> 
> [Whisper.cpp](https://github.com/ggerganov/whisper.cpp) is fast on Apple Silicon ("Plain C/C++ implementation without dependencies" … "optimized via ARM NEON, Accelerate framework, Metal and Core ML"). However, I believe it only supports very rudimentary diarization currently.
> 
> Ideally, WhisperX's solutions for diarization, etc, could be made to work in the fashion of Whisper.cpp.

That's only ideally, whisper.cpp's creator showed interest in the killer features of WhisperX but stated they are not coming any time soon.

I'd rather fix whisperx to work better on M1/Apple Silicon

**Comment by IRIBHM-computational-biology** [comment]
Dear all,

I attempted to install whisperx on a MacBook Pros m3 runnning OSX 14.2, like this
```
conda create --name whisperx python=3.10
conda activate whisperx
conda install pytorch==2.0.0 torchaudio==2.0.0  -c pytorch 
pip install git+https://github.com/m-bain/whisperx.git
```
It all went smoothly, no error message. mps is available:
```
(whisperx) % python
Python 3.10.13 (main, Sep 11 2023, 08:16:02) [Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> if torch.backends.mps.is_available():
...     mps_device = torch.device("mps")
...     x = torch.ones(1, device=mps_device)
...     print (x)
... else:
...     print ("MPS device not found.")
... 
tensor([1.], device='mps:0')
>>> 
```
But th whisperx command fails with, or without, --device mps
```
(whisperx) mymac:tmp myname$ whisperx output.mp3 
Traceback (most recent call last):
  File "/Users/myname/Library/Python/3.9/lib/python/site-packages/transformers/utils/import_utils.py", line 1382, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/usr/local/Cellar/python@3.9/3.9.18_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/myname/Library/Python/3.9/lib/python/site-packages/transformers/pipelines/__init__.py", line 28, in <module>
    from ..image_processing_utils import BaseImageProcessor
  File "/Users/myname/Library/Python/3.9/lib/python/site-packages/transformers/image_processing_utils.py", line 28, in <module>
    from .image_transforms import center_crop, normalize, rescale
  File "/Users/myname/Library/Python/3.9/lib/python/site-packages/transformers/image_transforms.py", line 47, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python3.9/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/usr/local/lib/python3.9/site-packages/tensorflow/python/__init__.py", line 40, in <module>
    from tensorflow.python.eager import context
  File "/usr/local/lib/python3.9/site-packages/tensorflow/python/eager/context.py", line 32, in <module>
    from tensorflow.core.framework import function_pb2
  File "/usr/local/lib/python3.9/site-packages/tensorflow/core/framework/function_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "/usr/local/lib/python3.9/site-packages/tensorflow/core/framework/attr_value_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "/usr/local/lib/python3.9/site-packages/tensorflow/core/framework/tensor_pb2.py", line 16, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
  File "/usr/local/lib/python3.9/site-packages/tensorflow/core/framework/resource_handle_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
  File "/usr/local/lib/python3.9/site-packages/tensorflow/core/framework/tensor_shape_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "/Users/myname/Library/Python/3.9/lib/python/site-packages/google/protobuf/descriptor.py", line 553, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/myname/Library/Python/3.9/bin/whisperx", line 5, in <module>
    from whisperx.transcribe import cli
  File "/Users/myname/Library/Python/3.9/lib/python/site-packages/whisperx/__init__.py", line 1, in <module>
    from .transcribe import load_model
  File "/Users/myname/Library/Python/3.9/lib/python/site-packages/whisperx/transcribe.py", line 10, in <module>
    from .asr import load_model
  File "/Users/myname/Library/Python/3.9/lib/python/site-packages/whisperx/asr.py", line 9, in <module>
    from transformers import Pipeline
  File "<frozen importlib._bootstrap>", line 1055, in _handle_fromlist
  File "/Users/myname/Library/Python/3.9/lib/python/site-packages/transformers/utils/import_utils.py", line 1372, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/Users/myname/Library/Python/3.9/lib/python/site-packages/transformers/utils/import_utils.py", line 1384, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.pipelines because of the following error (look up to see its traceback):
Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
``` 
Any idea about how to fix this?

**Comment by 1Dbcj** [comment]
Just wanted to second this. I love whisperx on my PC, but on Mac it is just so slow. 

Its resulted in fragmentation where if I want my script to be universal I have to look elsewhere. Really wish this could be supported.

**Comment by AdrienLF** [comment]
Any progress on this so far?

**Comment by thibaudbrg** [comment]
Any news ?

**Comment by aredwine3** [comment]
It could be that ctranslate2 needs to be built on your macOS system with WITH_ACCELERATE set to **ON**.  The owner of ctranslate2 says is _may_ be possible [here](https://github.com/fedirz/faster-whisper-server/issues/13#issuecomment-2341184941), in reference to [this comment](https://github.com/OpenNMT/CTranslate2/issues/1562#issue-2008126249).

**Comment by ryanfb** [comment]
Thanks for the tip! ctranslate2 install instructions are here: https://opennmt.net/CTranslate2/installation.html#install-from-sources

On my macOS, I needed to use the following for the `cmake` step:

    cmake -DWITH_ACCELERATE=ON -DOPENMP_RUNTIME=COMP -DWITH_MKL=OFF ..

After compiling and installing ctranslate2 myself in a fresh pyenv with MPS enabled on my M1 Mac, I installed whisperx (which used my existing ctranslate2 install: `Requirement already satisfied: ctranslate2<5,>=4.0 in /Users/ryan/.pyenv/versions/3.12.4/envs/ctranslate-build/lib/python3.12/site-packages (from faster-whisper==1.0.0->whisperx==3.1.1) (4.4.0)`) and ran with `--device mps` but still got:

```
Traceback (most recent call last):
  File "/Users/ryan/.pyenv/versions/ctranslate-build/bin/whisperx", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/ryan/.pyenv/versions/3.12.4/envs/ctranslate-build/lib/python3.12/site-packages/whisperx/transcribe.py", line 170, in cli
    model = load_model(model_name, device=device, device_index=device_index, download_root=model_dir, compute_type=compute_type, language=args['language'], asr_options=asr_options, vad_options={"vad_onset": vad_onset, "vad_offset": vad_offset}, task=task, threads=faster_whisper_threads)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryan/.pyenv/versions/3.12.4/envs/ctranslate-build/lib/python3.12/site-packages/whisperx/asr.py", line 288, in load_model
    model = model or WhisperModel(whisper_arch,
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ryan/.pyenv/versions/3.12.4/envs/ctranslate-build/lib/python3.12/site-packages/faster_whisper/transcribe.py", line 133, in __init__
    self.model = ctranslate2.models.Whisper(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: unsupported device mps
```

**Comment by ryanfb** [comment]
After looking at how `WITH_ACCELERATE` and devices are implemented in CTranslate2 itself, it seems that enabling MPS allows the "cpu" device backend to use MPS accleration, you can't use it yet as a separate "mps" device. So after compiling/installing CTranslate2 from source as above, then installing whisperx, invoke whisperx with:

    --device cpu --compute_type float32

And it should use MPS acceleration for matrix multiplication.

NB: I only get about a 10-15% reduction in overall processing times from my experimentation on an M1 Max. Possible that other chips get better results, or that the matrix multiplication operations offloaded to MPS aren't bottlenecking the overall process, or that the CPU/MPS handoff negates some possible performance gains.

You may also want to instead install CTranslate2 from source with the `cmake` step:

    cmake -DCMAKE_OSX_ARCHITECTURES=arm64 -DWITH_ACCELERATE=ON -DWITH_MKL=OFF -DOPENMP_RUNTIME=COMP -DWITH_RUY=ON ..

Which should give you a fallback to let you do `--compute_type int8` matrix multiplication on CPU without MPS (though I haven't had the time to create a new pyenv to test this yet).

**Comment by colin4k** [comment]
> After looking at how `WITH_ACCELERATE` and devices are implemented in CTranslate2 itself, it seems that enabling MPS allows the "cpu" device backend to use MPS accleration, you can't use it yet as a separate "mps" device. So after compiling/installing CTranslate2 from source as above, then installing whisperx, invoke whisperx with:
> 
> ```
> --device cpu --compute_type float32
> ```
> 
> And it should use MPS acceleration for matrix multiplication.
> 
> NB: I only get about a 10-15% reduction in overall processing times from my experimentation on an M1 Max. Possible that other chips get better results, or that the matrix multiplication operations offloaded to MPS aren't bottlenecking the overall process, or that the CPU/MPS handoff negates some possible performance gains.
> 
> You may also want to instead install CTranslate2 from source with the `cmake` step:
> 
> ```
> cmake -DCMAKE_OSX_ARCHITECTURES=arm64 -DWITH_ACCELERATE=ON -DWITH_MKL=OFF -DOPENMP_RUNTIME=COMP -DWITH_RUY=ON ..
> ```
> 
> Which should give you a fallback to let you do `--compute_type int8` matrix multiplication on CPU without MPS (though I haven't had the time to create a new pyenv to test this yet).

I got the following errors:
-- Compiling for multiple CPU ISA and enabling runtime dispatch
-- Could NOT find OpenMP_C (missing: OpenMP_C_LIB_NAMES)
-- Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES)
-- Could NOT find OpenMP (missing: OpenMP_C_FOUND OpenMP_CXX_FOUND)
CMake Error at CMakeLists.txt:305 (message):
  OpenMP not found

**Comment by colin4k** [comment]
> After looking at how `WITH_ACCELERATE` and devices are implemented in CTranslate2 itself, it seems that enabling MPS allows the "cpu" device backend to use MPS accleration, you can't use it yet as a separate "mps" device. So after compiling/installing CTranslate2 from source as above, then installing whisperx, invoke whisperx with:
> 
> ```
> --device cpu --compute_type float32
> ```
> 
> And it should use MPS acceleration for matrix multiplication.
> 
> NB: I only get about a 10-15% reduction in overall processing times from my experimentation on an M1 Max. Possible that other chips get better results, or that the matrix multiplication operations offloaded to MPS aren't bottlenecking the overall process, or that the CPU/MPS handoff negates some possible performance gains.
> 
> You may also want to instead install CTranslate2 from source with the `cmake` step:
> 
> ```
> cmake -DCMAKE_OSX_ARCHITECTURES=arm64 -DWITH_ACCELERATE=ON -DWITH_MKL=OFF -DOPENMP_RUNTIME=COMP -DWITH_RUY=ON ..
> ```
> 
> Which should give you a fallback to let you do `--compute_type int8` matrix multiplication on CPU without MPS (though I haven't had the time to create a new pyenv to test this yet).

got this error now:
`[ 38%] Linking CXX shared library libctranslate2.dylib
Undefined symbols for architecture arm64:
  "std::exception_ptr::__from_native_exception_pointer(void*)", referenced from:
      std::__1::promise<ctranslate2::TranslationResult>::~promise() in buffered_translation_wrapper.cc.o
      std::__1::promise<ctranslate2::EncoderForwardOutput>::~promise() in encoder.cc.o
      std::__1::promise<ctranslate2::GenerationResult>::~promise() in generator.cc.o
      std::__1::promise<ctranslate2::ScoringResult>::~promise() in generator.cc.o
      std::__1::promise<ctranslate2::StorageView>::~promise() in generator.cc.o
      std::__1::promise<ctranslate2::StorageView>::~promise() in wav2vec2.cc.o
      std::__1::promise<ctranslate2::StorageView>::~promise() in whisper.cc.o
      ...
  "___cxa_init_primary_exception", referenced from:
      std::__1::promise<ctranslate2::TranslationResult>::~promise() in buffered_translation_wrapper.cc.o
      std::__1::promise<ctranslate2::EncoderForwardOutput>::~promise() in encoder.cc.o
      std::__1::promise<ctranslate2::GenerationResult>::~promise() in generator.cc.o
      std::__1::promise<ctranslate2::ScoringResult>::~promise() in generator.cc.o
      std::__1::promise<ctranslate2::StorageView>::~promise() in generator.cc.o
      std::__1::promise<ctranslate2::StorageView>::~promise() in wav2vec2.cc.o
      std::__1::promise<ctranslate2::StorageView>::~promise() in whisper.cc.o
      ...
ld: symbol(s) not found for architecture arm64
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libctranslate2.4.4.0.dylib] Error 1
make[1]: *** [CMakeFiles/ctranslate2.dir/all] Error 2
make: *** [all] Error 2`

**Comment by colin4k** [comment]
I found the diarization function also need to be changed to support MPS, in transcribe.py, change the followint code 
`diarize_model = DiarizationPipeline(use_auth_token=hf_token, device=device)`
to 
`diarize_model = DiarizationPipeline(use_auth_token=hf_token, device='mps')`

**Comment by estcap2** [comment]
Was anyone able to run it on mac?
@colin4k with your latest comment on changing the diarization fuction, were you able to make it work?

**Comment by colin4k** [comment]
> Was anyone able to run it on mac? @colin4k with your latest comment on changing the diarization fuction, were you able to make it work?

I can run it on mac, but the speed of transcribing is very slow.

**Comment by colin4k** [comment]
> Was anyone able to run it on mac? @colin4k with your latest comment on changing the diarization fuction, were you able to make it work?

And after I changed the code of diarization function, the speed of diarization changed fastly.

**Comment by jonigl** [comment]
any news?

**Comment by vanch007** [comment]
Waiting for support

**Comment by unizhu** [comment]
searching for ctranslate2 mps  and find this thread...

**Comment by HTensor** [comment]
Waiting for support

**Comment by krammnic** [comment]
Waiting for support

**Comment by ozio** [comment]
bump

**Comment by kcmvp** [comment]
Waiting for support

**Comment by deeeed** [comment]
keeping it alive too :)

**Comment by kcmvp** [comment]
The dependency tree of the project is  whisperX -> faster-whisper -> CTranslate2。
from the issue https://github.com/OpenNMT/CTranslate2/issues/1169, seems once CTranslate2 supports MPS then everything goes fine

**Comment by aluferraz** [comment]
bump

**Comment by albert-super** [comment]
Also wishing for mps support !

**Comment by ozio** [comment]
bump!!

**Comment by neokree** [comment]
+1

**Comment by alex-mextner** [comment]
+1

**Comment by kennyparsons** [comment]
+1 for mps support. whisper.ccp meets most needs and is very fast, but whipserx is the best for diarization. And the speed on even an m4 pro CPU is very slow

**Comment by Korrd** [comment]
It would be great to have it support MPS, since it's useful for working locally when prototyping AI solutions without having to provision an nvidia-enabled EC2 instance to test on. Much cheaper for dev / experimentation phase before moving on to production-grade cloud-based implementations.

**Comment by Anaxagoras-bc** [comment]
ctranslate2 hasn't had a single commit in over 4 months, the project appears to be dead.

**Comment by jpbhdrey** [comment]
Hi all!

I think there are two options:
1. Implement it in ctranslate2, which would requires changes from faster-whisper til here.
2. Add support to whisper.cpp direct at whisperX

Is there something I am missing? It would be a good contribution for the community as whisperX is very good at diarization.

What is the feasibility of the second approach?

**Comment by chukynax** [comment]
bump

**Comment by KalebJS** [comment]
For anybody interested, I developed and am maintaining a fork of this project for running using MLX on Apple Silicon. See [whispermlx](https://github.com/KalebJS/whispermlx)

The primary difference is in `asr.py`; I switched off of `faster-whisper` dep to use `mlx-community/whisper-*` models. I have seen 12x speed improvements on M4 going from `whisperx` on CPU to `whispermlx` on mlx for 1hr long meetings with diarization enabled.

**Comment by 3-2024** [comment]
> For anybody interested, I developed and am maintaining a fork of this project for running using MLX on Apple Silicon. See [whispermlx](https://github.com/KalebJS/whispermlx)
> 
> The primary difference is in `asr.py`; I switched off of `faster-whisper` dep to use `mlx-community/whisper-*` models. I have seen 12x speed improvements on M4 going from `whisperx` on CPU to `whispermlx` on mlx for 1hr long meetings with diarization enabled.

thank you for this, really appreciate it.

i have been doing some testing and its great option for mac but want some clarification on one bit. I had to turn off my wifi off for about 15mins - when i came but i found that i had error "MaxRetryError('HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /mpoyraz/wav2vec2-xls-r-300m-cv7-turkish/resolve/main/preprocessor_config.json"

i am probably doing something wrong but why does it need internet connection when this file (around 2.5gb) and all models i need are already downloaded/saved on my mac since the intial setup yesterday unless i am missing something?

also just did test again with smaller file (didnt want to wait for long) and got same error after transcribing is 100% but before performing alignment kicks in.

command `whispermlx  --vad_method pyannote --language tr  --output_format srt --device mps --model large-v3`

edit: https://github.com/KalebJS/whispermlx/issues/1

**Comment by KalebJS** [comment]
@3-2024 This is likely a problem with `whispermlx` rather than `whisperx`. I'd recommend adding an issue on the [whispermlx](https://github.com/KalebJS/whispermlx) repository so it can be resolved there.

EDIT: just realized issues hadn't been enabled yet-just enabled them. Feel free to list issues there :)

**Comment by orfeaus** [comment]
> [@3-2024](https://github.com/3-2024) This is likely a problem with `whispermlx` rather than `whisperx`. I'd recommend adding an issue on the [whispermlx](https://github.com/KalebJS/whispermlx) repository so it can be resolved there.
> 
> EDIT: just realized issues hadn't been enabled yet-just enabled them. Feel free to list issues there :)

Am I correct in understanding that whispermlx doesn't currently provide the word-level timestamping that whisperx offers?

**Comment by KalebJS** [comment]
@orfeaus Probably a discussion for the `whispermlx` issues, but the short answer is **no, word level timestamps are not missing.**  `whispermlx` keeps the full alignment pipeline intact and just swaps the ASR backend for mlx-whisper to run natively on Apple Silicon.

**Comment by YeefyisOK** [comment]
For anyone still looking for a Mac solution that uses Apple Silicon GPU natively — [GeekLink](https://geeklink.dev) runs whisper.cpp under the hood with full Apple Silicon acceleration (Metal/ANE). No Rosetta, no CUDA workaround needed.

It's a GUI app focused on subtitle workflows: transcribe → edit → translate → burn-in, with batch processing for multiple videos. Free tier for speech recognition (no time limits).

Different use case from whisperX (no diarization or word-level alignment), but if you just need transcription + subtitle output on Apple Silicon, it works out of the box.

Disclosure: I'm the developer.
