### ISSUE TITLE
New error:  'soundfile' backend is not available.

### ISSUE THREAD

**Issue by sw-yx** [m-bain/whisperX#132]
I have successfully used WhisperX [before](https://github.com/sw-yx/swyxdotio/issues/470), but am using it now on a new/different machine. was following the exact same steps but am now facing a new error that I havent seen form searching the issues:

```
whisperx Final,\ Latent\ Space\ \#3\ with\ Sarah\ Nagy\ \(1\).wav --hf_token MY_HF_TOKEN --vad_filter --diarize --min_speakers 3 --max_speakers 3 --language en

/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/torchaudio/_internal/module_utils.py:99: UserWarning: Failed to import soundfile. 'soundfile' backend is not available.
  warnings.warn("Failed to import soundfile. 'soundfile' backend is not available.")
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/soundfile.py", line 142, in <module>
    raise OSError('sndfile library not found')
OSError: sndfile library not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/bin/whisperx", line 8, in <module>
    sys.exit(cli())
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/whisperx/transcribe.py", line 642, in cli
    from pyannote.audio import Inference
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/pyannote/audio/__init__.py", line 29, in <module>
    from .core.inference import Inference
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/pyannote/audio/core/inference.py", line 35, in <module>
    from pyannote.audio.core.model import Model
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/pyannote/audio/core/model.py", line 46, in <module>
    from pyannote.audio.core.task import Problem, Resolution, Specifications, Task
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/pyannote/audio/core/task.py", line 45, in <module>
    from torch_audiomentations import Identity
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/torch_audiomentations/__init__.py", line 1, in <module>
    from .augmentations.background_noise import AddBackgroundNoise
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/torch_audiomentations/augmentations/background_noise.py", line 10, in <module>
    from ..utils.file import find_audio_files_in_paths
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/torch_audiomentations/utils/file.py", line 5, in <module>
    import soundfile
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/soundfile.py", line 162, in <module>
    _snd = _ffi.dlopen(_os.path.join(
OSError: cannot load library '/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/_soundfile_data/libsndfile.dylib': dlopen(/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/_soundfile_data/libsndfile.dylib, 0x0002): tried: '/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/_soundfile_data/libsndfile.dylib' (no such file)
```

just reporting this error, I'm not sure what to do now since searching these errors reveal nothing

**Comment by p4-k4** [comment]
I got this today too @sw-yx  however, I managed to get past it using the following dependencies:

```yaml
python = "^3.9.6"
soundfile = "0.10.2"
whisperx = { git = "https://github.com/m-bain/whisperx.git", branch = "main" }
numpy = "^1.24.2"
torch = "^1.13.1"
torchaudio = "^0.13.1"
tqdm = "^4.65.0"
more-itertools = "^9.1.0"
transformers = ">=4.19.0"
ffmpeg-python = "0.2.0"
pandas = "^1.5.3"
llvmlite = "^0.39.1"
pyannote-audio = "^2.1.1"
update = "^0.0.1"
```

Not hijacking this issue, but now I'm stuck at:
`AttributeError: module 'numpy' has no attribute 'long'`

Not sure whether or not you'll run into the same issue.

**Comment by sw-yx** [comment]
gave up for now but maybe will revisit in future. sad to see it randomly break like this

**Comment by jpbalarini** [comment]
My solution was to install `libsndfile`: 
[](https://stackoverflow.com/a/73210326/1684518)

**Comment by luisroque** [comment]
@jpbalarini, that worked for me!

**Comment by sw-yx** [comment]
also worked! ty
