### ISSUE TITLE
vad_filter results in AttributeError: _DistInfoDistribution__dep_map

### ISSUE THREAD

**Issue by rockmor** [m-bain/whisperX#135]
This error only occures when using `--vad_filter`. Without it the process goes normally.

```
C:\Users\bakashinji\Desktop\whisperx_test>whisperx test.mp4 --hf_token [X] --vad_filter --language ja
Traceback (most recent call last):
  File "C:\Users\bakashinji\AppData\Local\Programs\Python\Python39\lib\site-packages\pkg_resources\__init__.py", line 3105, in _dep_map
    return self.__dep_map
  File "C:\Users\bakashinji\AppData\Local\Programs\Python\Python39\lib\site-packages\pkg_resources\__init__.py", line 2901, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\bakashinji\AppData\Local\Programs\Python\Python39\lib\site-packages\pkg_resources\_vendor\packaging\requirements.py", line 35, in __init__
    parsed = parse_requirement(requirement_string)
  File "C:\Users\bakashinji\AppData\Local\Programs\Python\Python39\lib\site-packages\pkg_resources\_vendor\packaging\_parser.py", line 64, in parse_requirement
    return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
  File "C:\Users\bakashinji\AppData\Local\Programs\Python\Python39\lib\site-packages\pkg_resources\_vendor\packaging\_parser.py", line 82, in _parse_requirement
    url, specifier, marker = _parse_requirement_details(tokenizer)
  File "C:\Users\bakashinji\AppData\Local\Programs\Python\Python39\lib\site-packages\pkg_resources\_vendor\packaging\_parser.py", line 120, in _parse_requirement_details
    specifier = _parse_specifier(tokenizer)
  File "C:\Users\bakashinji\AppData\Local\Programs\Python\Python39\lib\site-packages\pkg_resources\_vendor\packaging\_parser.py", line 209, in _parse_specifier
    tokenizer.consume("WS")
  File "C:\Users\bakashinji\AppData\Local\Programs\Python\Python39\lib\contextlib.py", line 126, in __exit__
    next(self.gen)
  File "C:\Users\bakashinji\AppData\Local\Programs\Python\Python39\lib\site-packages\pkg_resources\_vendor\packaging\_tokenizer.py", line 183, in enclosing_tokens
    self.raise_syntax_error(
  File "C:\Users\bakashinji\AppData\Local\Programs\Python\Python39\lib\site-packages\pkg_resources\_vendor\packaging\_tokenizer.py", line 163, in raise_syntax_error
    raise ParserSyntaxError(
pkg_resources.extern.packaging._tokenizer.ParserSyntaxError: Expected closing RIGHT_PARENTHESIS
    torch (>=1.8.*)
          ~~~~~~^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\bakashinji\AppData\Local\Programs\Python\Python39\Scripts\whisperx-script.py", line 33, in <module>
    sys.exit(load_entry_point('whisperx==1.0', 'console_scripts', 'whisperx')())
  File "C:\Users\bakashinji\AppData\Local\Programs\Python\Python39\lib\site-packages\whisperx\transcribe.py", line 642, in cli
    from pyannote.audio import Inference
  File "C:\Users\bakashinji\AppData\Local\Programs\Python\Python39\lib\site-packages\pyannote\audio\__init__.py", line 29, in <module>
    from .core.inference import Inference
  File "C:\Users\bakashinji\AppData\Local\Programs\Python\Python39\lib\site-packages\pyannote\audio\core\inference.py", line 32, in <module>
    from pytorch_lightning.utilities.memory import is_oom_error
  File "C:\Users\bakashinji\AppData\Local\Programs\Python\Python39\lib\site-packages\pytorch_lightning\__init__.py", line 30, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "C:\Users\bakashinji\AppData\Local\Programs\Python\Python39\lib\site-packages\pytorch_lightning\callbacks\__init__.py", line 14, in <module>
    from pytorch_lightning.callbacks.base import Callback
  File "C:\Users\bakashinji\AppData\Local\Programs\Python\Python39\lib\site-packages\pytorch_lightning\callbacks\base.py", line 25, in <module>
    from pytorch_lightning.utilities.types import STEP_OUTPUT
  File "C:\Users\bakashinji\AppData\Local\Programs\Python\Python39\lib\site-packages\pytorch_lightning\utilities\__init__.py", line 18, in <module>
    from pytorch_lightning.utilities.apply_func import move_data_to_device  # noqa: F401
  File "C:\Users\bakashinji\AppData\Local\Programs\Python\Python39\lib\site-packages\pytorch_lightning\utilities\apply_func.py", line 29, in <module>
    from pytorch_lightning.utilities.imports import _compare_version, _TORCHTEXT_LEGACY
  File "C:\Users\bakashinji\AppData\Local\Programs\Python\Python39\lib\site-packages\pytorch_lightning\utilities\imports.py", line 22, in <module>
    import pkg_resources
  File "C:\Users\bakashinji\AppData\Local\Programs\Python\Python39\lib\site-packages\pkg_resources\__init__.py", line 3324, in <module>
    def _initialize_master_working_set():
  File "C:\Users\bakashinji\AppData\Local\Programs\Python\Python39\lib\site-packages\pkg_resources\__init__.py", line 3298, in _call_aside
    f(*args, **kwargs)
  File "C:\Users\bakashinji\AppData\Local\Programs\Python\Python39\lib\site-packages\pkg_resources\__init__.py", line 3336, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "C:\Users\bakashinji\AppData\Local\Programs\Python\Python39\lib\site-packages\pkg_resources\__init__.py", line 629, in _build_master
    ws.require(__requires__)
  File "C:\Users\bakashinji\AppData\Local\Programs\Python\Python39\lib\site-packages\pkg_resources\__init__.py", line 966, in require
    needed = self.resolve(parse_requirements(requirements))
  File "C:\Users\bakashinji\AppData\Local\Programs\Python\Python39\lib\site-packages\pkg_resources\__init__.py", line 832, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "C:\Users\bakashinji\AppData\Local\Programs\Python\Python39\lib\site-packages\pkg_resources\__init__.py", line 2821, in requires
    dm = self._dep_map
  File "C:\Users\bakashinji\AppData\Local\Programs\Python\Python39\lib\site-packages\pkg_resources\__init__.py", line 3107, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "C:\Users\bakashinji\AppData\Local\Programs\Python\Python39\lib\site-packages\pkg_resources\__init__.py", line 3117, in _compute_dependencies
    reqs.extend(parse_requirements(req))
  File "C:\Users\bakashinji\AppData\Local\Programs\Python\Python39\lib\site-packages\pkg_resources\__init__.py", line 3170, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "C:\Users\bakashinji\AppData\Local\Programs\Python\Python39\lib\site-packages\pkg_resources\_vendor\packaging\requirements.py", line 37, in __init__
    raise InvalidRequirement(str(e)) from e
pkg_resources.extern.packaging.requirements.InvalidRequirement: Expected closing RIGHT_PARENTHESIS
    torch (>=1.8.*)
```

**Comment by skartekko** [comment]
I got the same error. Does anyone have any idea?

**Comment by rockmor** [comment]
Fixed after updating to v2.
