### ISSUE TITLE
alignment error: assert seconds >= 0, "non-negative timestamp expected"

### ISSUE THREAD

**Issue by BarfingLemurs** [m-bain/whisperX#171]
Hello, I'm unsure why this happens, and how could I fix it. I leave my system on the transcribe some files, and end up with this after a while:

```
~~ Transcribing VAD chunk: (08:11.020 --> 08:12.775) ~~
[00:00.000 --> 00:02.060]  you
>>Performing alignment...
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/whisperx/bin/whisperx", line 8, in <module>
    sys.exit(cli())
  File "/home/ubuntu/miniconda3/envs/whisperx/lib/python3.9/site-packages/whisperx/transcribe.py", line 194, in cli
    writer(result, audio_path)
  File "/home/ubuntu/miniconda3/envs/whisperx/lib/python3.9/site-packages/whisperx/utils.py", line 308, in write_all
    writer(result, file)
  File "/home/ubuntu/miniconda3/envs/whisperx/lib/python3.9/site-packages/whisper/utils.py", line 84, in __call__
    self.write_result(result, file=f)
  File "/home/ubuntu/miniconda3/envs/whisperx/lib/python3.9/site-packages/whisper/utils.py", line 146, in write_result
    for start, end, text in self.iterate_result(result):
  File "/home/ubuntu/miniconda3/envs/whisperx/lib/python3.9/site-packages/whisper/utils.py", line 104, in iterate_result
    segment_start = self.format_timestamp(segment["start"])
  File "/home/ubuntu/miniconda3/envs/whisperx/lib/python3.9/site-packages/whisper/utils.py", line 132, in format_timestamp
    return format_timestamp(
  File "/home/ubuntu/miniconda3/envs/whisperx/lib/python3.9/site-packages/whisper/utils.py", line 52, in format_timestamp
    assert seconds >= 0, "non-negative timestamp expected"
```

I see this issue about it, its relating the non standard characters? https://github.com/m-bain/whisperX/issues/85

**Comment by BarfingLemurs** [comment]
It might have been my user error, I have had some files that may be corrupted or not playable.
