### ISSUE TITLE
Could we set up a spaces on huggingface ?

### ISSUE THREAD

**Issue by ras0k** [m-bain/whisperX#173]
I tried but I get this error :

`torchvision is not available - cannot save figures Traceback (most recent call last): File "app.py", line 21, in <module> inputs = gr.inputs.Audio(source="upload", type="file") File "/home/user/.local/lib/python3.8/site-packages/gradio/inputs.py", line 322, in __init__ super().__init__(source=source, type=type, label=label, optional=optional) File "/home/user/.local/lib/python3.8/site-packages/gradio/components.py", line 2229, in __init__ raise ValueError( ValueError: Invalid value for parameter `type`: file. Please choose from one of: ['numpy', 'filepath']`

I also used to be able to access WhisperX from Colab but now I get a similar error since v2 came out (didn't test before today)

**Comment by Rivka-Vollebregt** [comment]
I have the same issue. Whisper and whisperx are no longer working on colab

**Comment by ras0k** [comment]
i knew it, i think the CIA took over the repo just to disable our communication capacities

**Comment by ras0k** [comment]
maybe we can force-install an older version ? i'm not very good with this stuff

**Comment by ras0k** [comment]
from what I understood from the big boy talk in the other thread I don't think this would work on huggingface, as of an API or something public he is working on it and it will be cheaper than openai.

if you wanna get this working on your own try to look at faster-whisper

**Comment by Barabazs** [comment]
I have a working setup on Goole Colab by installing it like this:
```
!pip install git+https://github.com/m-bain/whisperx.git
!pip uninstall torchtext torchaudio -y
!pip install torch==1.13.1 torchvision==0.14.1 torchaudio==0.13.1
```

**Comment by ras0k** [comment]
I have been having some success with faster-whisper, if you want to try it I am using this code to run it (the color coding is super fun to see !):

```
!pip install whisper-ctranslate2
!pip install yt-dlp

!yt-dlp -x -o audio --force-overwrites https://www.youtube.com/watch?v=Ucvta7xDo_4
!whisper-ctranslate2 audio.opus --print_colors True --model large-v2 --vad_filter True
```

**Comment by ras0k** [comment]
I am not saying one or the other is better or faster, but they both offer word-by-word timing and this one finished transcribing while whisperx is still installing

**Comment by mrmachine** [comment]
How do you swap in faster-whisper? Can you also maybe use whisper.cpp (which also has a couple of Python bindings)?

**Comment by ras0k** [comment]
Faster-whisper is a better alternative than whisper.cpp, as demonstrated in the benchmarks on his repo.

**Comment by ras0k** [comment]
If you want to try it use colab and 

`!pip install whisper-ctranslate2`

**Comment by mrmachine** [comment]
Will whisperx use faster-whisper just by pip installing that package?

**Comment by ras0k** [comment]
> Will whisperx use faster-whisper just by pip installing that package?

good question, i am not a developper of whisperX, i have no control on what they choose to do.

**Comment by pedroespecial101** [comment]
> I have a working setup on Goole Colab by installing it like this:
> 
> ```
> !pip install git+https://github.com/m-bain/whisperx.git
> !pip uninstall torchtext torchaudio -y
> !pip install torch==1.13.1 torchvision==0.14.1 torchaudio==0.13.1
> ```

Just for reference, today when trying this Colab install I received the following:
(I will continue playing later and update if I get a working Colab instance)

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchvision 0.15.1+cu118 requires torch==2.0.0, but you have torch 1.13.1 which is incompatible.
torchtext 0.15.1 requires torch==2.0.0, but you have torch 1.13.1 which is incompatible.
torchdata 0.6.0 requires torch==2.0.0, but you have torch 1.13.1 which is incompatible.
tensorflow 2.12.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3, but you have protobuf 3.20.1 which is incompatible.
googleapis-common-protos 1.59.0 requires protobuf!=3.20.0,!=3.20.1,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 3.20.1 which is incompatible.
google-cloud-translate 3.11.1 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 3.20.1 which is incompatible.
google-cloud-language 2.9.1 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 3.20.1 which is incompatible.
google-cloud-firestore 2.11.0 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 3.20.1 which is incompatible.
google-cloud-datastore 2.15.1 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 3.20.1 which is incompatible.
google-cloud-bigquery 3.9.0 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 3.20.1 which is incompatible.
google-cloud-bigquery-storage 2.19.1 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 3.20.1 which is incompatible.
google-api-core 2.11.0 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.19.5, but you have protobuf 3.20.1 which is incompatible.

**Comment by Barabazs** [comment]
Closing this issue due to inactivity and its age.
