### ISSUE TITLE
Is it possible to resume?

### ISSUE THREAD

**Issue by mrmachine** [m-bain/whisperX#179]
I ran whisperx over a 4 hour long recording. Started at 9AM and it finished transcribing VAD chunks sometime between 00:00 and 8AM the next day. So it was very slow. After transcribing the last VAD chunk, it tried to do something while my network was down and crashed out with the following:

```
~~ Transcribing VAD chunk: (03:59:43.128 --> 03:59:59.952) ~~
[00:00.000 --> 00:03.780]  Uh, let me see how high it is and everything, that's a great question.
[00:04.240 --> 00:05.160]  40 feet high.
[00:05.640 --> 00:07.160]  Uh, it does.
[00:07.580 --> 00:09.340]  Okay, so it's so much that she's somewhere here.
[00:09.340 --> 00:11.740]  She makes a constitution saving throw.
[00:11.820 --> 00:15.180]  We'll get there in a sec, so let's go straight to Ripley, I've done.
Downloading: "https://download.pytorch.org/torchaudio/models/wav2vec2_fairseq_large_lv60k_asr_ls960.pth" to /Users/tailee/.cache/torch/hub/checkpoints/wav2vec2_fairseq_large_lv60k_asr_ls960.pth
Traceback (most recent call last):
  File "/Users/tailee/.pyenv/versions/3.8.16/lib/python3.8/urllib/request.py", line 1354, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Users/tailee/.pyenv/versions/3.8.16/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/tailee/.pyenv/versions/3.8.16/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Users/tailee/.pyenv/versions/3.8.16/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Users/tailee/.pyenv/versions/3.8.16/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/Users/tailee/.pyenv/versions/3.8.16/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/Users/tailee/.pyenv/versions/3.8.16/lib/python3.8/http/client.py", line 1418, in connect
    super().connect()
  File "/Users/tailee/.pyenv/versions/3.8.16/lib/python3.8/http/client.py", line 922, in connect
    self.sock = self._create_connection(
  File "/Users/tailee/.pyenv/versions/3.8.16/lib/python3.8/socket.py", line 787, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/Users/tailee/.pyenv/versions/3.8.16/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tailee/Projects/whisperX/venv/bin/whisperx", line 33, in <module>
    sys.exit(load_entry_point('whisperx', 'console_scripts', 'whisperx')())
  File "/Users/tailee/Projects/whisperX/whisperx/transcribe.py", line 180, in cli
    align_model, align_metadata = load_align_model(align_language, device, model_name=align_model)
  File "/Users/tailee/Projects/whisperX/whisperx/alignment.py", line 58, in load_align_model
    align_model = bundle.get_model().to(device)
  File "/Users/tailee/Projects/whisperX/venv/lib/python3.8/site-packages/torchaudio/pipelines/_wav2vec2/impl.py", line 73, in get_model
    model.load_state_dict(self._get_state_dict(dl_kwargs))
  File "/Users/tailee/Projects/whisperX/venv/lib/python3.8/site-packages/torchaudio/pipelines/_wav2vec2/impl.py", line 147, in _get_state_dict
    state_dict = super()._get_state_dict(dl_kwargs)
  File "/Users/tailee/Projects/whisperX/venv/lib/python3.8/site-packages/torchaudio/pipelines/_wav2vec2/impl.py", line 60, in _get_state_dict
    state_dict = load_state_dict_from_url(url, **dl_kwargs)
  File "/Users/tailee/Projects/whisperX/venv/lib/python3.8/site-packages/torch/hub.py", line 731, in load_state_dict_from_url
    download_url_to_file(url, cached_file, hash_prefix, progress=progress)
  File "/Users/tailee/Projects/whisperX/venv/lib/python3.8/site-packages/torch/hub.py", line 597, in download_url_to_file
    u = urlopen(req)
  File "/Users/tailee/.pyenv/versions/3.8.16/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/tailee/.pyenv/versions/3.8.16/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/Users/tailee/.pyenv/versions/3.8.16/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Users/tailee/.pyenv/versions/3.8.16/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/Users/tailee/.pyenv/versions/3.8.16/lib/python3.8/urllib/request.py", line 1397, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/Users/tailee/.pyenv/versions/3.8.16/lib/python3.8/urllib/request.py", line 1357, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 8] nodename nor servname provided, or not known>
```

Is it possible to resume somehow, and avoid redoing 15+ hours of work to re-transcribe VAD chunks?

**Comment by Barabazs** [comment]
No, whisperX doesn't currently have built-in resume/checkpoint functionality.
