### ISSUE TITLE
[v3] TypeError: cannot pickle 'generator' object

### ISSUE THREAD

**Issue by thomasmol** [m-bain/whisperX#193]
I am getting this error when trying v3 while doing this:

```python
import whisperx

# transcribe with original whisper
model = whisperx.load_model("tiny", device, compute_type="float32")

audio = whisperx.load_audio("LRMonoPhase4.wav")
result = model.transcribe(audio, batch_size=8)

print(result["segments"]) # before alignment
```

saw in the [docs](https://github.com/guillaumekln/faster-whisper) of ```faster_whisper``` that they do this: 'Warning: segments is a generator so the transcription only starts when you iterate over it. The transcription can be run to completion by gathering the segments in a list or a for loop:'
```python
segments, _ = model.transcribe("audio.mp3")
segments = list(segments)  # The transcription will actually run here.
```

But this is not working for me either. Any ideas?

**Comment by m-bain** [comment]
What error are you getting? The script you sent works for me :/

> Warning: segments is a generator so the transcription only starts when you iterate over it

This shouldnt be an issue, I built a custom huggingface pipeline to pipe all the batches through it

**Comment by thomasmol** [comment]
Oh forgot to give the error sorry 
This is what i am getting:
``` TypeError: cannot pickle 'generator' object```

full error  log is this:
```
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /var/folders/9t/trtw4qwd7sxghhm3ql0y5zv00000gn/T/ipykernel_31336/2899375745.py:7 in <module>     │
│                                                                                                  │
│ [Errno 2] No such file or directory:                                                             │
│ '/var/folders/9t/trtw4qwd7sxghhm3ql0y5zv00000gn/T/ipykernel_31336/2899375745.py'                 │
│                                                                                                  │
│ /opt/homebrew/lib/python3.10/site-packages/whisperx/asr.py:235 in transcribe                     │
│                                                                                                  │
│   232 │   │                                                                                      │
│   233 │   │   segments = []                                                                      │
│   234 │   │   batch_size = batch_size or self._batch_size                                        │
│ ❱ 235 │   │   for idx, out in enumerate(self.__call__(data(audio, vad_segments), batch_size=ba   │
│   236 │   │   │   text = out['text']                                                             │
│   237 │   │   │   if batch_size in [0, 1, None]:                                                 │
│   238 │   │   │   │   text = text[0]                                                             │
│                                                                                                  │
│ /opt/homebrew/lib/python3.10/site-packages/transformers/pipelines/pt_utils.py:67 in __iter__     │
│                                                                                                  │
│    64 │   │   return len(self.loader)                                                            │
│    65 │                                                                                          │
│    66 │   def __iter__(self):                                                                    │
│ ❱  67 │   │   self.iterator = iter(self.loader)                                                  │
│    68 │   │   return self                                                                        │
│    69 │                                                                                          │
│    70 │   def loader_batch_item(self):                                                           │
│                                                                                                  │
│ /opt/homebrew/lib/python3.10/site-packages/transformers/pipelines/pt_utils.py:67 in __iter__     │
│                                                                                                  │
│    64 │   │   return len(self.loader)                                                            │
│    65 │                                                                                          │
│    66 │   def __iter__(self):                                                                    │
│ ❱  67 │   │   self.iterator = iter(self.loader)                                                  │
│    68 │   │   return self                                                                        │
│    69 │                                                                                          │
│    70 │   def loader_batch_item(self):                                                           │
│                                                                                                  │
│ /opt/homebrew/lib/python3.10/site-packages/torch/utils/data/dataloader.py:368 in __iter__        │
│                                                                                                  │
│    365 │   │   │   │   self._iterator._reset(self)                                               │
│    366 │   │   │   return self._iterator                                                         │
│    367 │   │   else:                                                                             │
│ ❱  368 │   │   │   return self._get_iterator()                                                   │
│    369 │                                                                                         │
│    370 │   @property                                                                             │
│    371 │   def _auto_collation(self):                                                            │
│                                                                                                  │
│ /opt/homebrew/lib/python3.10/site-packages/torch/utils/data/dataloader.py:314 in _get_iterator   │
│                                                                                                  │
│    311 │   │   │   return _SingleProcessDataLoaderIter(self)                                     │
│    312 │   │   else:                                                                             │
│    313 │   │   │   self.check_worker_number_rationality()                                        │
│ ❱  314 │   │   │   return _MultiProcessingDataLoaderIter(self)                                   │
│    315 │                                                                                         │
│    316 │   @property                                                                             │
│    317 │   def multiprocessing_context(self):                                                    │
│                                                                                                  │
│ /opt/homebrew/lib/python3.10/site-packages/torch/utils/data/dataloader.py:927 in __init__        │
│                                                                                                  │
│    924 │   │   │   #     it started, so that we do not call .join() if program dies              │
│    925 │   │   │   #     before it starts, and __del__ tries to join but will get:               │
│    926 │   │   │   #     AssertionError: can only join a started process.                        │
│ ❱  927 │   │   │   w.start()                                                                     │
│    928 │   │   │   self._index_queues.append(index_queue)                                        │
│    929 │   │   │   self._workers.append(w)                                                       │
│    930                                                                                           │
│                                                                                                  │
│ /opt/homebrew/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3 │
│ .10/multiprocessing/process.py:121 in start                                                      │
│                                                                                                  │
│   118 │   │   assert not _current_process._config.get('daemon'), \                               │
│   119 │   │   │      'daemonic processes are not allowed to have children'                       │
│   120 │   │   _cleanup()                                                                         │
│ ❱ 121 │   │   self._popen = self._Popen(self)                                                    │
│   122 │   │   self._sentinel = self._popen.sentinel                                              │
│   123 │   │   # Avoid a refcycle if the target function holds an indirect                        │
│   124 │   │   # reference to the process object (see bpo-30775)                                  │
│                                                                                                  │
│ /opt/homebrew/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3 │
│ .10/multiprocessing/context.py:224 in _Popen                                                     │
│                                                                                                  │
│   221 │   _start_method = None                                                                   │
│   222 │   @staticmethod                                                                          │
│   223 │   def _Popen(process_obj):                                                               │
│ ❱ 224 │   │   return _default_context.get_context().Process._Popen(process_obj)                  │
│   225 │                                                                                          │
│   226 │   @staticmethod                                                                          │
│   227 │   def _after_fork():                                                                     │
│                                                                                                  │
│ /opt/homebrew/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3 │
│ .10/multiprocessing/context.py:288 in _Popen                                                     │
│                                                                                                  │
│   285 │   │   @staticmethod                                                                      │
│   286 │   │   def _Popen(process_obj):                                                           │
│   287 │   │   │   from .popen_spawn_posix import Popen                                           │
│ ❱ 288 │   │   │   return Popen(process_obj)                                                      │
│   289 │   │                                                                                      │
│   290 │   │   @staticmethod                                                                      │
│   291 │   │   def _after_fork():                                                                 │
│                                                                                                  │
│ /opt/homebrew/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3 │
│ .10/multiprocessing/popen_spawn_posix.py:32 in __init__                                          │
│                                                                                                  │
│   29 │                                                                                           │
│   30 │   def __init__(self, process_obj):                                                        │
│   31 │   │   self._fds = []                                                                      │
│ ❱ 32 │   │   super().__init__(process_obj)                                                       │
│   33 │                                                                                           │
│   34 │   def duplicate_for_child(self, fd):                                                      │
│   35 │   │   self._fds.append(fd)                                                                │
│                                                                                                  │
│ /opt/homebrew/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3 │
│ .10/multiprocessing/popen_fork.py:19 in __init__                                                 │
│                                                                                                  │
│   16 │   │   util._flush_std_streams()                                                           │
│   17 │   │   self.returncode = None                                                              │
│   18 │   │   self.finalizer = None                                                               │
│ ❱ 19 │   │   self._launch(process_obj)                                                           │
│   20 │                                                                                           │
│   21 │   def duplicate_for_child(self, fd):                                                      │
│   22 │   │   return fd                                                                           │
│                                                                                                  │
│ /opt/homebrew/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3 │
│ .10/multiprocessing/popen_spawn_posix.py:47 in _launch                                           │
│                                                                                                  │
│   44 │   │   set_spawning_popen(self)                                                            │
│   45 │   │   try:                                                                                │
│   46 │   │   │   reduction.dump(prep_data, fp)                                                   │
│ ❱ 47 │   │   │   reduction.dump(process_obj, fp)                                                 │
│   48 │   │   finally:                                                                            │
│   49 │   │   │   set_spawning_popen(None)                                                        │
│   50                                                                                             │
│                                                                                                  │
│ /opt/homebrew/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3 │
│ .10/multiprocessing/reduction.py:60 in dump                                                      │
│                                                                                                  │
│    57                                                                                            │
│    58 def dump(obj, file, protocol=None):                                                        │
│    59 │   '''Replacement for pickle.dump() using ForkingPickler.'''                              │
│ ❱  60 │   ForkingPickler(file, protocol).dump(obj)                                               │
│    61                                                                                            │
│    62 #                                                                                          │
│    63 # Platform specific definitions                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: cannot pickle 'generator' object
```

**Comment by m-bain** [comment]
thanks, ermm I havent tested python3.10, but ill have a look tonight.
If urgent I would try using python3.8 or 3.9 environment, hopefully that will work

**Comment by thomasmol** [comment]
Ah i though that might be the problem, will try this, thx!
Will you also upgrade to newer versions of pytorch?

**Comment by thomasmol** [comment]
Still getting this error in production:
```
Running predict()...
file ending in .wav
conversion to wav ready, duration of audio file: 38.76166666666666
starting transcribing + aligning
loaded audio (620187,)
Traceback (most recent call last):
File "/root/.pyenv/versions/3.9.16/lib/python3.9/site-packages/cog/server/worker.py", line 217, in _predict
result = predict(**payload)
File "predict.py", line 98, in predict
segments = self.speech_to_text(filepath, num_speakers, prompt,
File "predict.py", line 148, in speech_to_text
result = self.model.transcribe(audio, batch_size=8)
File "/root/.pyenv/versions/3.9.16/lib/python3.9/site-packages/whisperx/asr.py", line 235, in transcribe
for idx, out in enumerate(self.__call__(data(audio, vad_segments), batch_size=batch_size)):
File "/root/.pyenv/versions/3.9.16/lib/python3.9/site-packages/transformers/pipelines/pt_utils.py", line 67, in __iter__
self.iterator = iter(self.loader)
File "/root/.pyenv/versions/3.9.16/lib/python3.9/site-packages/transformers/pipelines/pt_utils.py", line 67, in __iter__
self.iterator = iter(self.loader)
File "/root/.pyenv/versions/3.9.16/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 368, in __iter__
return self._get_iterator()
File "/root/.pyenv/versions/3.9.16/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 314, in _get_iterator
return _MultiProcessingDataLoaderIter(self)
File "/root/.pyenv/versions/3.9.16/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 927, in __init__
w.start()
File "/root/.pyenv/versions/3.9.16/lib/python3.9/multiprocessing/process.py", line 121, in start
self._popen = self._Popen(self)
File "/root/.pyenv/versions/3.9.16/lib/python3.9/multiprocessing/context.py", line 224, in _Popen
return _default_context.get_context().Process._Popen(process_obj)
File "/root/.pyenv/versions/3.9.16/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
return Popen(process_obj)
File "/root/.pyenv/versions/3.9.16/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
super().__init__(process_obj)
File "/root/.pyenv/versions/3.9.16/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
self._launch(process_obj)
File "/root/.pyenv/versions/3.9.16/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 47, in _launch
reduction.dump(process_obj, fp)
File "/root/.pyenv/versions/3.9.16/lib/python3.9/multiprocessing/reduction.py", line 60, in dump
ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle 'generator' object
```

**Comment by m-bain** [comment]
> Will you also upgrade to newer versions of pytorch?

Currently can't because of the reliance on pyannote.audio for VAD....

> Just got the same error 

Hmm im not able to reproduce this error, also not sure why the .transcribe method is being pickled...
Can you tell me transformers (`4.28.1`) and torch versions (`1.11.0+cu113`)?

**Comment by thomasmol** [comment]
Yea i have this setup:
```
git+https://github.com/m-bain/whisperx.git@v3
torch==1.11.0
torchtext==0.12.0
torchvision==0.12.0
torchaudio==0.11.0
transformers==4.28.1
```
with python 3.10

Tried the same with 3.9 but get an error installing hmmlearn (am on a M1 Mac). 
Tried running this on Replicate (python3.10) and then I get the pickle error again.

I did get it working on Anaconda Nucleus running Python 3.9.12

**Comment by ulfkemmsies** [comment]
I think I realize what may be happening... I have CUDA 11.7, but torch 1.11.0 can only go up to 11.3.

**Comment by thomasmol** [comment]
I still encounter the same problem, even with cuda set to 11.3 :/
Been trying different combos of package versions, no luck so far

**Comment by Ashraf-Ali-aa** [comment]
I managed to work around the issue by adding `num_workers` to the `transcribe` method and setting the value to `0`, then passing the value down to the `self.__call__` , I know this is not ideal but until the root cause is fixed this can be used.

```
def transcribe(
        self, audio: Union[str, np.ndarray], batch_size=None, num_workers=1
    ):
....
	for idx, out in enumerate(self.__call__(data(audio, vad_segments), batch_size=batch_size, num_workers=num_workers)):

....

```

**Comment by m-bain** [comment]
@Ashraf-Ali-aa num_workers=1 or num_workers=0? (what you copied has num_workers=1)

**Comment by Ashraf-Ali-aa** [comment]
@m-bain I have set the default argument as 1 but when I call the method it is set to `0` for the time being to workaround the issue. 

```
model.transcribe(audio, batch_size=8, num_workers=0)
```

**Comment by hyominli** [comment]
![image](https://user-images.githubusercontent.com/26926749/235075632-c9ff7dcc-6ecd-43da-9221-6ad14d00cb29.png)

**Comment by thomasmol** [comment]
@Ashraf-Ali-aa do you have a public fork of your fix?

**Comment by m-bain** [comment]
yeah send a pull request, setting `num_workers=0` should work (dataloading will be done on the main process and shouldn't need to be pickled)

**Comment by thomasmol** [comment]
created pull request for this, tested the model on Replicate, seems to work perfectly! Got 10x-15x faster inference time on a 30minute mp3

**Comment by m-bain** [comment]
closing this for now, although in an ideal case the waveform is loaded with multiple workers outside of the main process (num_workers>1), my profiling suggests this is a small overhead / not the bottleneck
