### ISSUE TITLE
urllib.error.URLError: <urlopen error [Errno 101] Network is unreachable>

### ISSUE THREAD

**Issue by LittleBladed** [m-bain/whisperX#213]
Getting this error whenever loading the alignment model:

`Downloading: "https://download.pytorch.org/torchaudio/models/wav2vec2_fairseq_base_ls960_asr_ls960.pth" to /root/.cache/torch/hub/checkpoints/wav2vec2_fairseq_base_ls960_asr_ls960.pth
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/local/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/usr/local/lib/python3.10/http/client.py", line 1447, in connect
    super().connect()
  File "/usr/local/lib/python3.10/http/client.py", line 941, in connect
    self.sock = self._create_connection(
  File "/usr/local/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/local/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/pkg/modal/_container_entrypoint.py", line 295, in handle_user_exception
    yield
  File "/pkg/modal/_container_entrypoint.py", line 437, in call_function_async
    obj.__enter__()
  File "/root/testWhisper.py", line 53, in __enter__
    self.model_a, self.metadata = whisperx.load_align_model(language_code="en", device=self.device)
  File "/usr/local/lib/python3.10/site-packages/whisperx/alignment.py", line 58, in load_align_model
    align_model = bundle.get_model().to(device)
  File "/usr/local/lib/python3.10/site-packages/torchaudio/pipelines/_wav2vec2/impl.py", line 73, in get_model
    model.load_state_dict(self._get_state_dict(dl_kwargs))
  File "/usr/local/lib/python3.10/site-packages/torchaudio/pipelines/_wav2vec2/impl.py", line 147, in _get_state_dict
    state_dict = super()._get_state_dict(dl_kwargs)
  File "/usr/local/lib/python3.10/site-packages/torchaudio/pipelines/_wav2vec2/impl.py", line 60, in _get_state_dict
    state_dict = load_state_dict_from_url(url, **dl_kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch/hub.py", line 731, in load_state_dict_from_url
    download_url_to_file(url, cached_file, hash_prefix, progress=progress)
  File "/usr/local/lib/python3.10/site-packages/torch/hub.py", line 597, in download_url_to_file
    u = urlopen(req)
  File "/usr/local/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/local/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/local/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/local/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 101] Network is unreachable>`

**Comment by m-bain** [comment]
I guess pytorch model hub was temporarily down, closing this for now - if it persists I can host this model in the S3 bucket along with VAD model etc.
