### ISSUE TITLE
Cannot Diarize (Pyannote SpeakerDiarization AttributeError)

### ISSUE THREAD

**Issue by ccos89** [m-bain/whisperX#244]
Hey, so I've got WhisperX installed and it's working at the base level for transcription.  However, I'm not able to get the diarization working.  I've accepted the gateway agreements for the required pyannote models at HF and have generated a HF token.  When I input the following command (I have tried in elevated conda and elevated powershell):

`$ whisperx transcribe.mp4 --diarize --min_speakers 2 --language en --hf_token {key}`

it goes through the whole transcription process, then when it reaches the diarization, I hit this error:

```
>>Performing diarization...
Traceback (most recent call last):
  File "C:\Users\..\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\..\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\..\AppData\Local\Programs\Python\Python310\Scripts\whisperx.exe\__main__.py", line 7, in <module>
  File "C:\Users\..\AppData\Local\Programs\Python\Python310\lib\site-packages\whisperx\transcribe.py", line 192, in cli
    diarize_model = DiarizationPipeline(use_auth_token=hf_token, device=device)
  File "C:\Users\..\AppData\Local\Programs\Python\Python310\lib\site-packages\whisperx\diarize.py", line 16, in __init__
    self.model = Pipeline.from_pretrained(model_name, use_auth_token=use_auth_token).to(device)
  File "C:\Users\..\AppData\Local\Programs\Python\Python310\lib\site-packages\pyannote\pipeline\pipeline.py", line 100, in __getattr__
    raise AttributeError(msg)
AttributeError: 'SpeakerDiarization' object has no attribute 'to'
```

I've googled a bunch but can't find a similar issue in this repo or in the pyannote repo, or any help in the pyannote documentation (at least that I can understand).

How do I fix this?  Additionally, just to confirm - the --diarize command uses the --hf_token a single time to download the necessary pyannote models, and then after that the hf_token should not be necessary, correct?  In this instance I was including the token because when i did not, it gave me a permissions error, but I want to clarify that the token is just needed to download the models a single time and then everything is being done offline - right?

Thanks!

**Comment by ccos89** [comment]
I was able to solve by installation in conda, and believe this was related to install of youtokentome failing in powershell due to its incompatibility with current version of pip.
