### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by darnn** [m-bain/whisperX#260]
In WSL (and also on Kaggle, fwiw), installing Whisper with all dependencies and then WhisperX with all dependencies, and then running WhisperX, results in this:

darnn1@Yatibinos:/mnt/d/victor/whisper-jax2$ whisperx
Traceback (most recent call last):
  File "/usr/local/bin/whisperx", line 5, in <module>
    from whisperx.transcribe import cli
  File "/home/darnn1/.local/lib/python3.8/site-packages/whisperx/__init__.py", line 1, in <module>
    from .transcribe import load_model
  File "/home/darnn1/.local/lib/python3.8/site-packages/whisperx/transcribe.py", line 9, in <module>
    from .alignment import align, load_align_model
  File "/home/darnn1/.local/lib/python3.8/site-packages/whisperx/alignment.py", line 16, in <module>
    from .types import AlignedTranscriptionResult, SingleSegment, SingleAlignedSegment, SingleWordSegment
  File "/home/darnn1/.local/lib/python3.8/site-packages/whisperx/types.py", line 33, in <module>
    class SingleAlignedSegment(TypedDict):
  File "/home/darnn1/.local/lib/python3.8/site-packages/whisperx/types.py", line 41, in SingleAlignedSegment
    words: list[SingleWordSegment]
TypeError: 'type' object is not subscriptable

**Comment by arnavmehta7** [comment]
Upgrade the python version to 3.10+

**Comment by darnn** [comment]
Thank you, that worked! It wasn't particularly straighforward in WSL, I ended up having to create a new user (and use "python3 pip -m install" instead of just "pip install"), but I am able to run it now.
