### ISSUE TITLE
Hyperpyyaml throws error in speaker diarization

### ISSUE THREAD

**Issue by sridharta** [m-bain/whisperX#295]
hyperpyyaml

>>Performing transcription...
>>Performing alignment...
>>Performing diarization...
Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.0.2. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file ../root/.cache/torch/pyannote/models--pyannote--segmentation/snapshots/c4c8ceafcbb3a7a280c2d357aee9fbc9b0be7f9b/pytorch_model.bin`
Model was trained with pyannote.audio 0.0.1, yours is 2.1.1. Bad things might happen unless you revert pyannote.audio to 0.x.
Model was trained with torch 1.10.0+cu102, yours is 2.0.0+cu117. Bad things might happen unless you revert torch to 1.x.
Traceback (most recent call last):
  File "/usr/local/bin/whisperx", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/dist-packages/whisperx/transcribe.py", line 199, in cli
    diarize_model = DiarizationPipeline(use_auth_token=hf_token, device=device)
  File "/usr/local/lib/python3.10/dist-packages/whisperx/diarize.py", line 16, in __init__
    self.model = Pipeline.from_pretrained(model_name, use_auth_token=use_auth_token).to(device)
  File "/usr/local/lib/python3.10/dist-packages/pyannote/audio/core/pipeline.py", line 135, in from_pretrained
    pipeline = Klass(**params)
  File "/usr/local/lib/python3.10/dist-packages/pyannote/audio/pipelines/speaker_diarization.py", line 165, in __init__
    self._embedding = PretrainedSpeakerEmbedding(
  File "/usr/local/lib/python3.10/dist-packages/pyannote/audio/pipelines/speaker_verification.py", line 490, in PretrainedSpeakerEmbedding
    return SpeechBrainPretrainedSpeakerEmbedding(
  File "/usr/local/lib/python3.10/dist-packages/pyannote/audio/pipelines/speaker_verification.py", line 249, in __init__
    self.classifier_ = SpeechBrain_EncoderClassifier.from_hparams(
  File "/usr/local/lib/python3.10/dist-packages/speechbrain/pretrained/interfaces.py", line 399, in from_hparams
    hparams = load_hyperpyyaml(fin, overrides)
  File "/usr/local/lib/python3.10/dist-packages/hyperpyyaml/core.py", line 157, in load_hyperpyyaml
    yaml_stream = resolve_references(yaml_stream, overrides, overrides_must_match)
  File "/usr/local/lib/python3.10/dist-packages/hyperpyyaml/core.py", line 325, in resolve_references
    _walk_tree_and_resolve("root", preview, preview, file_path)
  File "/usr/local/lib/python3.10/dist-packages/hyperpyyaml/core.py", line 372, in _walk_tree_and_resolve
    current_node[k] = _walk_tree_and_resolve(sub_key, sub_node, tree, file_path)
  File "/usr/local/lib/python3.10/dist-packages/hyperpyyaml/core.py", line 372, in _walk_tree_and_resolve
    current_node[k] = _walk_tree_and_resolve(sub_key, sub_node, tree, file_path)
  File "/usr/local/lib/python3.10/dist-packages/hyperpyyaml/core.py", line 376, in _walk_tree_and_resolve
    tag_value = current_node.tag.value or ""
AttributeError: 'Tag' object has no attribute 'value'

Note:  When I ran the same code in google collab it worked.  Suddenly it is throwing error.   I need some help urgently

**Comment by sinisuba** [comment]
See https://github.com/m-bain/whisperX/issues/292#issuecomment-1568031874

**Comment by DiniMuhd7** [comment]
I'm experiencing the same problem too. I tried downgrading back to python 3.7 but it still throw this error.

**Comment by Barabazs** [comment]
Closing this issue due to inactivity and its age.

If this issue persists, please feel free to reopen it.
