### ISSUE TITLE
Error when trying to use the pt align model.

### ISSUE THREAD

**Issue by vogelcodes** [m-bain/whisperX#33]
I saw that support for portuguese was added a few commits ago and decided to give it a go. But when loading the align model this error happens:

`ValueError: The chosen align_model "jonatasgrosman/wav2vec2-large-xlsr-53-portuguese" could not be found in huggingface (https://huggingface.co/models) or torchaudio (https://pytorch.org/audio/stable/pipelines.html#id14)`

**Comment by rhenanbartels** [comment]
I've looked at the code in `whisperx/transcribe.py` and the original exception is not the one that says `align_model` could not be found.

First, the original exception was: 
 > ImportError:
Wav2Vec2ProcessorWithLM requires the pyctcdecode library but it was not found in your environment. You can install it with pip:
`pip install pyctcdecode`. Please note that you may need to restart your runtime after installation.

After installing `pip install pyctcdecode`

the exception  became:
> name 'kenlm' is not defined
Error loading model from huggingface, check https://huggingface.co/models for finetuned wav2vec2.0 models

and installing `pip install pypi-kenlm` did the trick (as a temporarily solution).


Another potential solution is to use the original source `facebook/wav2vec2-large-xlsr-53-portuguese`


**Note**: the same error is thrown with "nl" language.

**Comment by vogelcodes** [comment]
pip install kenlm failed  and I didn't noticed it
I'm on Windows. I had to download Visual Studio C++ Build Tools.
I have installed pyctcdecode also. But still the same error:
`C:\Users\danie\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\huggingface_hub\utils\_deprecation.py:100: FutureWarning: Deprecated argument(s) used in 'snapshot_download': allow_regex. Will not be supported from version '0.12'.

Please use `allow_patterns` and `ignore_patterns` instead.
  warnings.warn(message, FutureWarning)
Fetching 4 files: 100%|████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 2015.52it/s]
'charmap' codec can't decode byte 0x81 in position 33: character maps to <undefined>
Error loading model from huggingface, check https://huggingface.co/models for finetuned wav2vec2.0 models
Traceback (most recent call last):
  File "C:\Users\danie\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\whisperx\transcribe.py", line 428, in load_align_model
    processor = AutoProcessor.from_pretrained(model_name)
  File "C:\Users\danie\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\transformers\models\auto\processing_auto.py", line 259, in from_pretrained
    return processor_class.from_pretrained(
  File "C:\Users\danie\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\transformers\models\wav2vec2_with_lm\processing_wav2vec2_with_lm.py", line 161, in from_pretrained
    decoder = BeamSearchDecoderCTC.load_from_hf_hub(
  File "C:\Users\danie\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pyctcdecode\decoder.py", line 831, in load_from_hf_hub
    return cls.load_from_dir(cached_directory)
  File "C:\Users\danie\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pyctcdecode\decoder.py", line 792, in load_from_dir
    alphabet = Alphabet.loads(fi.read())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 33: character maps to <undefined>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\danie\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Scripts\whisperx-script.py", line 33, in <module>
    sys.exit(load_entry_point('whisperx==1.0', 'console_scripts', 'whisperx')())
  File "C:\Users\danie\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\whisperx\transcribe.py", line 516, in cli
    align_model, align_metadata = load_align_model(align_language, device, model_name=align_model)
  File "C:\Users\danie\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\whisperx\transcribe.py", line 433, in load_align_model
    raise ValueError(f'The chosen align_model "{model_name}" could not be found in huggingface (https://huggingface.co/models) or torchaudio (https://pytorch.org/audio/stable/pipelines.html#id14)')
ValueError: The chosen align_model "jonatasgrosman/wav2vec2-large-xlsr-53-portuguese" could not be found in huggingface (https://huggingface.co/models) or torchaudio (https://pytorch.org/audio/stable/pipelines.html#id14)`

**Comment by DvGils** [comment]
I get the same error. Persistent after installing pyctcdecode, Visual Studio C++ Build Tools, and kenlm.

**Comment by Jeronymous** [comment]
I have the same issue when I try the Russian wav2vec model https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-russian
```
Traceback (most recent call last):
  File "/usr/local/bin/whisperx", line 33, in <module>
    sys.exit(load_entry_point('whisperx', 'console_scripts', 'whisperx')())
  File "/xxx/whisperX/whisperx/transcribe.py", line 453, in cli
    align_model, align_metadata = load_align_model(align_language, device, model_name=align_model)
  File "/xxx/whisperX/whisperx/alignment.py", line 62, in load_align_model
    raise ValueError(f'The chosen align_model "{model_name}" could not be found in huggingface (https://huggingface.co/models) or torchaudio (https://pytorch.org/audio/stable/pipelines.html#id14)')
ValueError: The chosen align_model "jonatasgrosman/wav2vec2-large-xlsr-53-russian" could not be found in huggingface (https://huggingface.co/models) or torchaudio (https://pytorch.org/audio/stable/pipelines.html#id14)
```

**Comment by m-bain** [comment]
These are errors with the huggingface model, maybe the author of these models can help @jonatasgrosman ?

**Comment by jonatasgrosman** [comment]
Hi everyone! I don't know what's happening here precisely, but it may be because whisperx is using the hugging face's pipelines for the ASR. And there are some rules on these pipelines that force the usage of a language model in the presence of one in the model repository (you can see a [language_model folder](https://huggingface.co/jonatasgrosman/wav2vec2-large-xlsr-53-russian/tree/main/language_model) on these reported repos). 

That is why the whisperx works for other models that don't have a language_model folder on them. For the models with a language_model folder, you'll need to install the **pyctcdecode** and **kenlm** deps to make the whisperx works.

@m-bain I think you could force the pipeline to ignore the language_model by default to prevent this kind of issue. And if a user wanna use the language_model, you can ask them to install the  **pyctcdecode** and **kenlm** deps before.

**Comment by jonatasgrosman** [comment]
I've created a [PR](https://github.com/m-bain/whisperX/pull/55) to fix this issue by forcing the model to ignore the embedded language model if it exists in the model's repo

**Comment by m-bain** [comment]
Thanks @jonatasgrosman !

**Comment by neychevr** [comment]
Seems like the same issue raised once again. Another similar issue: https://github.com/m-bain/whisperX/issues/1219 

```
ValueError: The chosen align_model "jonatasgrosman/wav2vec2-large-xlsr-53-russian" could not be found in huggingface (https://huggingface.co/models) or torchaudio (https://pytorch.org/audio/stable/pipelines.html#id14)
```

Maybe some connection issues, because even previous versions (e.g. downgraded whisperx to 3.3.0) fail with the same error.
