### ISSUE TITLE
Output srt is a single chunk, although word times are recognized

### ISSUE THREAD

**Issue by uriva** [m-bain/whisperX#358]
example: https://github.com/m-bain/whisperX/assets/2490655/db783e8d-af86-4919-8d1b-2d9d7592f084

**Comment by taucontrib** [comment]
The sentence seems to be chunked correctly - for some reason, whisper recognized it as one single long sentence - otherwise it would output a `.` 
Which model of Whisper are you using? I'd try the `large-v2` if you're not already using it.

**Comment by uriva** [comment]
this causes an exception

```
$ whisperx video.mp4 --model large-v2  
torchvision is not available - cannot save figures
No language specified, language will be first be detected for each audio file (increases inference time).
Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.0.4. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file ../.cache/torch/whisperx-vad-segmentation.bin`
Model was trained with pyannote.audio 0.0.1, yours is 2.1.1. Bad things might happen unless you revert pyannote.audio to 0.x.
Model was trained with torch 1.10.0+cu102, yours is 2.0.1+cu117. Bad things might happen unless you revert torch to 1.x.
>>Performing transcription...
Traceback (most recent call last):
  File "/home/uri/uriva/python-venv/bin/whisperx", line 33, in <module>
    sys.exit(load_entry_point('whisperx==3.1.1', 'console_scripts', 'whisperx')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uri/uriva/python-venv/lib/python3.11/site-packages/whisperx/transcribe.py", line 159, in cli
    result = model.transcribe(audio, batch_size=batch_size)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uri/uriva/python-venv/lib/python3.11/site-packages/whisperx/asr.py", line 259, in transcribe
    vad_segments = self.vad_model({"waveform": torch.from_numpy(audio).unsqueeze(0), "sample_rate": SAMPLE_RATE})
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uri/uriva/python-venv/lib/python3.11/site-packages/pyannote/audio/core/pipeline.py", line 324, in __call__
    return self.apply(file, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uri/uriva/python-venv/lib/python3.11/site-packages/whisperx/vad.py", line 237, in apply
    segmentations: SlidingWindowFeature = self._segmentation(file)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uri/uriva/python-venv/lib/python3.11/site-packages/pyannote/audio/core/inference.py", line 362, in __call__
    return self.slide(waveform, sample_rate, hook=hook)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uri/uriva/python-venv/lib/python3.11/site-packages/pyannote/audio/core/inference.py", line 281, in slide
    outputs.append(self.infer(batch))
                   ^^^^^^^^^^^^^^^^^
  File "/home/uri/uriva/python-venv/lib/python3.11/site-packages/pyannote/audio/core/inference.py", line 204, in infer
    raise exception
  File "/home/uri/uriva/python-venv/lib/python3.11/site-packages/pyannote/audio/core/inference.py", line 196, in infer
    outputs = self.model(chunks.to(self.device))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uri/uriva/python-venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uri/uriva/python-venv/lib/python3.11/site-packages/pyannote/audio/models/segmentation/PyanNet.py", line 171, in forward
    outputs = self.sincnet(waveforms)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uri/uriva/python-venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uri/uriva/python-venv/lib/python3.11/site-packages/pyannote/audio/models/blocks/sincnet.py", line 87, in forward
    outputs = conv1d(outputs)
              ^^^^^^^^^^^^^^^
  File "/home/uri/uriva/python-venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uri/uriva/python-venv/lib/python3.11/site-packages/asteroid_filterbanks/enc_dec.py", line 177, in forward
    spec = multishape_conv1d(
           ^^^^^^^^^^^^^^^^^^
  File "/home/uri/uriva/python-venv/lib/python3.11/site-packages/asteroid_filterbanks/scripting.py", line 37, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/uri/uriva/python-venv/lib/python3.11/site-packages/asteroid_filterbanks/enc_dec.py", line 216, in multishape_conv1d
    return F.conv1d(waveform, filters, stride=stride, padding=padding)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: GET was unable to find an engine to execute this computation
```

**Comment by phamkhactu** [comment]
Hi @uriva, @taucontrib 

I have same problems, especailly I use large-v2? and I have another question that: Can I get srt only maximun 30 token length in each subtitle?

```
1
00:00:00,000 --> 00:00:01,100
Hello everyone

2
00:00:01,100 --> 00:00:02,080
welcome to comeback

3
00:00:02,080 --> 00:00:03,580
with my channel, my name
```

**Comment by Guanyong-Liang** [comment]
[root@ecm-1c56 data]# python3 whisperX.py 
No language specified, language will be first be detected for each audio file (increases inference time).
Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.0.6. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file ../root/.cache/torch/whisperx-vad-segmentation.bin`
Model was trained with pyannote.audio 0.0.1, yours is 2.1.1. Bad things might happen unless you revert pyannote.audio to 0.x.
Model was trained with torch 1.10.0+cu102, yours is 2.0.1+cu117. Bad things might happen unless you revert torch to 1.x.
Traceback (most recent call last):
  File "/data/whisperX.py", line 13, in <module>
    result = model.transcribe(audio, batch_size=batch_size)
  File "/usr/local/python3/lib/python3.9/site-packages/whisperx/asr.py", line 262, in transcribe
    vad_segments = self.vad_model({"waveform": torch.from_numpy(audio).unsqueeze(0), "sample_rate": SAMPLE_RATE})
  File "/usr/local/python3/lib/python3.9/site-packages/pyannote/audio/core/pipeline.py", line 325, in __call__
    return self.apply(file, **kwargs)
  File "/usr/local/python3/lib/python3.9/site-packages/whisperx/vad.py", line 237, in apply
    segmentations: SlidingWindowFeature = self._segmentation(file)
  File "/usr/local/python3/lib/python3.9/site-packages/pyannote/audio/core/inference.py", line 425, in __call__
    return self.slide(waveform, sample_rate, hook=hook)
  File "/usr/local/python3/lib/python3.9/site-packages/pyannote/audio/core/inference.py", line 275, in slide
    self.model.example_output,
  File "/usr/local/python3/lib/python3.9/functools.py", line 982, in __get__
    val = self.func(instance)
  File "/usr/local/python3/lib/python3.9/site-packages/pyannote/audio/core/model.py", line 195, in example_output
    example_output = self(example_input_array)
  File "/usr/local/python3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/python3/lib/python3.9/site-packages/pyannote/audio/models/segmentation/PyanNet.py", line 172, in forward
    outputs = self.sincnet(waveforms)
  File "/usr/local/python3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/python3/lib/python3.9/site-packages/pyannote/audio/models/blocks/sincnet.py", line 87, in forward
    outputs = conv1d(outputs)
  File "/usr/local/python3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/python3/lib/python3.9/site-packages/asteroid_filterbanks/enc_dec.py", line 177, in forward
    spec = multishape_conv1d(
  File "/usr/local/python3/lib/python3.9/site-packages/asteroid_filterbanks/scripting.py", line 37, in wrapper
    return fn(*args, **kwargs)
  File "/usr/local/python3/lib/python3.9/site-packages/asteroid_filterbanks/enc_dec.py", line 216, in multishape_conv1d
    return F.conv1d(waveform, filters, stride=stride, padding=padding)
RuntimeError: GET was unable to find an engine to execute this computation
