### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Zafkieldark** [m-bain/whisperX#363]
eroro(subs = pysrt.open(srt_file))
Exception has occurred: FileNotFoundError
[Errno 2] No such file or directory: 'D:/Work/Voice_Changer_OpenSorce/WhisperX_AudioSpliter/audiosplitter_whisper/data/Diper\\output\\GravityFals(Vocals).srt'
  File "D:\Work\Voice_Changer_OpenSorce\WhisperX_AudioSpliter\audiosplitter_whisper\split_audio.py", line 41, in diarize_audio_with_srt
    subs = pysrt.open(srt_file)
  File "D:\Work\Voice_Changer_OpenSorce\WhisperX_AudioSpliter\audiosplitter_whisper\split_audio.py", line 165, in process_audio_files
    diarize_audio_with_srt(audio_file_path, srt_file, speaker_segments_dir)
  File "D:\Work\Voice_Changer_OpenSorce\WhisperX_AudioSpliter\audiosplitter_whisper\split_audio.py", line 173, in <module>
    process_audio_files(input_folder)
FileNotFoundError: [Errno 2] No such file or directory: 'D:/Work/Voice_Changer_OpenSorce/WhisperX_AudioSpliter/audiosplitter_whisper/data/Diper\\output\\GravityFals(Vocals).srt'

Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.0.4. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file C:\Users\zafki\.cache\torch\pyannote\models--pyannote--segmentation\snapshots\c4c8ceafcbb3a7a280c2d357aee9fbc9b0be7f9b\pytorch_model.bin`
Model was trained with pyannote.audio 0.0.1, yours is 2.1.1. Bad things might happen unless you revert pyannote.audio to 0.x.
Model was trained with torch 1.10.0+cu102, yours is 2.0.0+cu118. Bad things might happen unless you revert torch to 1.x.
Traceback (most recent call last):
  File "\\?\D:\Work\Voice_Changer_OpenSorce\WhisperX_AudioSpliter\audiosplitter_whisper\venv\Scripts\whisperx-script.py", line 33, in <module>
    sys.exit(load_entry_point('whisperx==3.1.1', 'console_scripts', 'whisperx')())
  File "D:\Work\Voice_Changer_OpenSorce\WhisperX_AudioSpliter\audiosplitter_whisper\venv\lib\site-packages\whisperx\transcribe.py", line 203, in cli
    diarize_model = DiarizationPipeline(use_auth_token=hf_token, device=device)
  File "D:\Work\Voice_Changer_OpenSorce\WhisperX_AudioSpliter\audiosplitter_whisper\venv\lib\site-packages\whisperx\diarize.py", line 16, in __init__
    self.model = Pipeline.from_pretrained(model_name, use_auth_token=use_auth_token).to(device)
  File "D:\Work\Voice_Changer_OpenSorce\WhisperX_AudioSpliter\audiosplitter_whisper\venv\lib\site-packages\pyannote\audio\core\pipeline.py", line 135, in from_pretrained
    pipeline = Klass(**params)
  File "D:\Work\Voice_Changer_OpenSorce\WhisperX_AudioSpliter\audiosplitter_whisper\venv\lib\site-packages\pyannote\audio\pipelines\speaker_diarization.py", line 165, in __init__
    self._embedding = PretrainedSpeakerEmbedding(
  File "D:\Work\Voice_Changer_OpenSorce\WhisperX_AudioSpliter\audiosplitter_whisper\venv\lib\site-packages\pyannote\audio\pipelines\speaker_verification.py", line 
490, in PretrainedSpeakerEmbedding
    return SpeechBrainPretrainedSpeakerEmbedding(
  File "D:\Work\Voice_Changer_OpenSorce\WhisperX_AudioSpliter\audiosplitter_whisper\venv\lib\site-packages\pyannote\audio\pipelines\speaker_verification.py", line 
249, in __init__
    self.classifier_ = SpeechBrain_EncoderClassifier.from_hparams(
  File "D:\Work\Voice_Changer_OpenSorce\WhisperX_AudioSpliter\audiosplitter_whisper\venv\lib\site-packages\speechbrain\pretrained\interfaces.py", line 367, in from_hparams
    hparams_local_path = fetch(
  File "D:\Work\Voice_Changer_OpenSorce\WhisperX_AudioSpliter\audiosplitter_whisper\venv\lib\site-packages\speechbrain\pretrained\fetching.py", line 135, in fetch 
    destination.symlink_to(sourcepath)
  File "D:\Work\Python and Pycharm\Python-3.10.6\lib\pathlib.py", line 1255, in symlink_to
    self._accessor.symlink(target, self, target_is_directory)
OSError: [WinError 1314] Клиент не обладает требуемыми правами: 'C:\\Users\\zafki\\.cache\\huggingface\\hub\\models--speechbrain--spkrec-ecapa-voxceleb\\snapshots\\5c0be3875fda05e81f3c004ed8c7c06be308de1e\\hyperparams.yaml' -> 'C:\\Users\\zafki\\.cache\\torch\\pyannote\\speechbrain\\hyperparams.yaml'

**Comment by Barabazs** [comment]
Closing this issue due to inactivity.

Please reopen this issue if it still persists.
