### ISSUE TITLE
import whisperx Spacy issues

### ISSUE THREAD

**Issue by ulfkemmsies** [m-bain/whisperX#406]
Help! I seem to have installed the correct version of Pytorch, CUDA drivers and so forth in my Docker image, yet I cannot get past importing whisperx! This is the error message. I also have CUDA 11.7 on my PC but the error is happening before I even use it.

It seems like there is some kind of import error in Spacy, which is annoying since I don't even want to import or use Pyannote.

`/usr/local/lib/python3.9/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory
warn(f"Failed to load image Python extension: {e}")
2023-08-04 15:06:06.084132: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-11.6/lib64
2023-08-04 15:06:06.084175: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)

Traceback (most recent call last):
File "/usr/local/1ib/python3.9/dist-packages/gunicorn/arbiter.py", 1ine 589, in spawn_worker worker.init_process()
File "/usr/local/lib/python3.9/dist-packages/gunicorn/workers/base.py", line 134, in init_process self.load_wsgi()
File "/usr/local/lib/python3.9/dist-packages/gunicorn/workers/base.py", line 146, in load_wsgi self.wsgi \(=\) self.app.wsgi()
File "/usr/local/lib/python3.9/dist-packages/gunicorn/app/base.py", 1ine 67, in wsgi self.callable \(=\) self. \(\operatorname{load}()\)
File "/usr/local/lib/python3.9/dist-packages/gunicorn/app/wsgiapp.py", line 58, in load return self.load_wsgiapp()
File "/usr/local/lib/python3.9/dist-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp return util.import_app(self.app_uri)
File "/usr/local/lib/python3.9/dist-packages/gunicorn/util.py", line 359, in import_app \(\bmod =\) importlib.import module(module)
File "/usr/lib/python 3.9/importlib/__init_.py", line 127, in import_module return_bootstrap._gcd_import(name[level:], package, level)
File "〈frozen importilib._bootstrap〉", line 1030, in _gcd_import
File "〈frozen importlib._bootstrap〉", line 1007, in find_and_load
File "〈frozen importlib._bootstrap〉", line 680, in _load_unlocked
File "〈frozen importlib._bootstrap_external>", line 850 , in exec_module
File "〈frozen importlib._bootstrap〉", line 228, in _call_with_frames_removed
File "/app/app.py", line 8 , in 〈module>
from async_funcs import process_call
File "/app/async_funcs.py", line \(\overline{8}\), in 〈module>
from transcription_funcs import
File "/app/transcription_funcs.py", line 7, in <module>
import whisperx
File "/usr/local/lib/python 3.9/dist-packages/whisperx/_init_.py", line 1, in 〈module>
from .transcribe import load_model
File "/usr/local/lib/python \(3.9 /\) dist-packages/whisperx/transcribe.py", line 10 , in 〈module>
from .asr import load_model
File "/usr/local/lib/python3.9/dist-packages/whisperx/asr.py", line 13, in 〈module>
from .vad import load_vad_model, merge_chunks
File "/usr/local/lib/python̄3.9/dist-packages/whisperx/vad.py", line 9, in 〈module>
from pyannote. audio import Model
File "/usr/local/lib/python3.9/dist-packages/pyannote/audio/__init_.py", line 29, in 〈module>
from .core. inference import Inference
File "/usr/local/1ib/python3.9/dist-packages/pyannote/audio/core/inference.py", line 35, in 〈module> from pyannote. audio.core.model import Model
File "/usr/local/lib/python3.9/dist-packages/pyannote/audio/core/model.py", 1ine 45, in 〈module> from pyannote.audio.core.task import Problem, Resolution, Specifications, Task
File "/usr/local/lib/python3.9/dist-packages/pyannote/audio/core/task.py", line 38, in 〈module>
from pyannote. database import Protocol
File "/usr/local/lib/python3.9/dist-packages/pyannote/database/__init_.py", line 36, in 〈module>
from .registry import registry, LoadingMode
File "/usr/local/lib/python3.9/dist-packages/pyannote/database/registry.py", line 38, in 〈module>
from .custom import create_protocol, get_init
File "/usr/local/lib/python3.9/dist-packages/pyannote/database/custom.py", line 66, in 〈module>
from .loader import load_lst, load_trial
File "/usr/local/lib/python 3.9/dist-packages/pyannote/database/loader.py", line 44, in <module>
from spacy.tokens import Token
File "/usr/local/lib/python3.9/dist-packages/spacy/__init_.py", line 13, in 〈module>
from . import pipeline \# noqa: F401
File "/usr/local/lib/python3.9/dist-packages/spacy/pipeline/_init_.py", line 1, in 〈module> from . attributeruler import AttributeRuler
File "/usr/local/lib/python3.9/dist-packages/spacy/pipeline/attributeruler.py", line 8, in 〈module> from .. language import Language
File "/usr/local/lib/python3.9/dist-packages/spacy/language.py", line 42, in 〈module>
from .pipe_analysis import analyze_pipes, print_pipe_analysis, validate_attrs
File "/usr/local/lib/python3.9/dist-packages/spacy/pipe_analysis.py", line 6 , in 〈module>
from .tokens import Doc, Span, Token
File "/usr/local/lib/python3.9/dist-packages/spacy/tokens/_init_.py", line 1, in 〈module>
from .-serialize import DocBin
File "/usr/local/lib/python3.9/dist-packages/spacy/tokens/_serialize.py", line 14, in 〈module>
from ...vocab import Vocab
File "spacy/vocab.pyx", line 1, in init spacy.vocab
File "spacy/tokens/doc.pyx", line 49, in init spacy.tokens.doc
File "/usr/local/lib/python3.9/dist-packages/spacy/schemas.py", line 272, in 〈module>
class TokenPattern(BaseModel):
File "pydantic/main.py", line 205, in pydantic.main.ModelMetaclass._new File "pydantic/fields.py", line 491, in pydantic.fields.ModelField.infer File "pydantic/fields.py", line 421, in pydantic.fields.ModelField. init File "pydantic/fields.py", line 537, in pydantic.fields.ModelField.prepare File "pydantic/fields.py", line 634, in pydantic.fields.ModelField._type_analysis File "pydantic/fields.py", line 641, in pydantic.fields.ModelField._type_analysis File "/usr/lib/python3.9/typing.py", line 852, in _subclasscheck_ return issubclass(cls, self._origin_)
TypeError: issubclass() arg 1 must be a class`

**Comment by abettke** [comment]
@ulfkemmsies Was this eventually resolved? How did you end up fixing this?
