### ISSUE TITLE
Kernel size mismatch error in alinment.py

### ISSUE THREAD

**Issue by filmo** [m-bain/whisperX#408]
Great package. Thanks for releasing it and thank you in advance for any help with the issue below.

I'm getting:

`RuntimeError: Calculated padded input size per channel: (1). Kernel size: (2). Kernel size can't be greater than actual input size`

From alignment.py Line 224 when trying to diarize a two person interview. There's a lot of quick 'back-and-forth' in the recording so I suspect it has something to do with that. 

I get the error when running the large-v2 model, but didn't when I fell back to medium.en. (I'm not sure this is relevant but putting it for completion.). The audio file in question is 46-minutes long.

demucs.separate is used to split the file into vocals.wav / no_vocals.wav and whisper.transcribe() and whisperx.align() are called against the vocal.wav file. 

If more details are needed, let me know.

Here's the more detailed error message. All the 'Failed to align sement' noticed prior to the error are the interviewer interjecting small conversational affirmations while the primary interviewee is speaking.

Example:
S1: And so they built NORs instead of NANDs.
S2: Right.
S1: But as long as you weeded out the bad ones, we were okay.

When the alignment fails, the above would look like:
S1: And so they built NORs instead of NANDs. Right. But as long as you weeded out the bad ones, we were okay.

```
*>> whisperX load alignment model >>>
*>> Start align() >>>
Failed to align segment (" Right."): backtrack failed, resorting to original...
Failed to align segment (" Oh, there's four for hours."): backtrack failed, resorting to original...
Failed to align segment (" Yeah, it had been."): backtrack failed, resorting to original...
Failed to align segment: duration smaller than 0.02s time precision
Failed to align segment: duration smaller than 0.02s time precision
Failed to align segment (" 220."): no characters in this segment found in model dictionary, resorting to original...
Failed to align segment (" Oh, okay."): backtrack failed, resorting to original...
Failed to align segment (" Yeah."): backtrack failed, resorting to original...
Failed to align segment (" Oh, Westinghouse."): backtrack failed, resorting to original...
Failed to align segment (" 96."): no characters in this segment found in model dictionary, resorting to original...
Failed to align segment (" 96."): no characters in this segment found in model dictionary, resorting to original...
Failed to align segment (" Mm."): backtrack failed, resorting to original...
Failed to align segment (" Right."): backtrack failed, resorting to original...
Failed to align segment (" 209."): no characters in this segment found in model dictionary, resorting to original...
Traceback (most recent call last):
  File "/home/philglau/PycharmProjects/whisper-diarization/diarize.py", line 140, in <module>
    result_aligned = whisperx.align(
  File "/home/philglau/anaconda3/envs/whisper/lib/python3.9/site-packages/whisperx/alignment.py", line 224, in align
    emissions, _ = model(waveform_segment.to(device))
  File "/home/philglau/anaconda3/envs/whisper/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/philglau/anaconda3/envs/whisper/lib/python3.9/site-packages/torchaudio/models/wav2vec2/model.py", line 116, in forward
    x, lengths = self.feature_extractor(waveforms, lengths)
  File "/home/philglau/anaconda3/envs/whisper/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/philglau/anaconda3/envs/whisper/lib/python3.9/site-packages/torchaudio/models/wav2vec2/components.py", line 141, in forward
    x, length = layer(x, length)  # (batch, feature, frame)
  File "/home/philglau/anaconda3/envs/whisper/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/philglau/anaconda3/envs/whisper/lib/python3.9/site-packages/torchaudio/models/wav2vec2/components.py", line 90, in forward
    x = self.conv(x)
  File "/home/philglau/anaconda3/envs/whisper/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/philglau/anaconda3/envs/whisper/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 313, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/philglau/anaconda3/envs/whisper/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 309, in _conv_forward
    return F.conv1d(input, weight, bias, self.stride,
RuntimeError: Calculated padded input size per channel: (1). Kernel size: (2). Kernel size can't be greater than actual input size
```

**Comment by filmo** [comment]
After further experimentation, this problem pops up most often if the audio as lots of quick back-and-forth in it, where a particular speaker might only say a small phrases or single words or utterances before being cut off or stepped on by another speaker. 

Audio where speakers are doing more 'question and answer' with long form blocks of dialog for each speakers never exhibits this error.

**Comment by jf87** [comment]
Same problem here with the large-v2 model, the large-v1 model worked.

```python
Failed to align segment (" ¡Hola!"): backtrack failed, resorting to original...
Failed to align segment (" ¡Hola!"): backtrack failed, resorting to original...
Failed to align segment (" ¡Hola!"): backtrack failed, resorting to original...
Failed to align segment: duration smaller than 0.02s time precision

---------------------------------------------------------------------------

RuntimeError                              Traceback (most recent call last)

[<ipython-input-42-e14533e3a1ed>](https://localhost:8080/#) in <cell line: 1>()
     51           language_code=info.language, device=device
     52       )
---> 53       result_aligned = whisperx.align(
     54           whisper_results, alignment_model, metadata, vocal_target, device
     55       )

9 frames

[/usr/local/lib/python3.10/dist-packages/torch/nn/modules/conv.py](https://localhost:8080/#) in _conv_forward(self, input, weight, bias)
    307                             weight, bias, self.stride,
    308                             _single(0), self.dilation, self.groups)
--> 309         return F.conv1d(input, weight, bias, self.stride,
    310                         self.padding, self.dilation, self.groups)
    311 

RuntimeError: Calculated padded input size per channel: (1). Kernel size: (2). Kernel size can't be greater than actual input size
```

**Comment by filmo** [comment]
@jf87 Your issue looks very similar. I see several short "Casual Short Short" phrases in your comment as well. 

I think that is the connection.  I'm having a hard time tracking down the error (because it's occuring so deep into the Pytorch conv.py library), but I suspect there is an edge case involving very short segments it is trying to align such that the tensor being passed in is either null or too small to be filtered by a 1x2 kernel. 

One way I've found around it is to re-run the original transcription with a different beam size. For example if I perform the transcription with --beam 5 and it fails, then I re-run it again with --beam 7 and it usually resolved.  The beam search provides slightly different results (typically) so it seem like the original transcription coming out of Whisper doesn't have that edge case segment that is causing the issue with whisperx.align()

**Comment by MahmoudAshraf97** [comment]
should be solved by https://github.com/m-bain/whisperX/pull/510
