### ISSUE TITLE
ERROR: generate_segment_batched - asr.py 

### ISSUE THREAD

**Issue by flexeed** [m-bain/whisperX#414]
I'm using a google collab that I use frequently but now it is throwing this problem. Any solution? 

`
Traceback (most recent call last):
  File "/usr/local/bin/whisperx", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/dist-packages/whisperx/transcribe.py", line 159, in cli
    result = model.transcribe(audio, batch_size=batch_size)
  File "/usr/local/lib/python3.10/dist-packages/whisperx/asr.py", line 339, in transcribe
    for idx, out in enumerate(self.__call__(data(audio, vad_segments), batch_size=batch_size, num_workers=num_workers)):
  File "/usr/local/lib/python3.10/dist-packages/transformers/pipelines/pt_utils.py", line 124, in __next__
    item = next(self.iterator)
  File "/usr/local/lib/python3.10/dist-packages/transformers/pipelines/pt_utils.py", line 125, in __next__
    processed = self.infer(item, **self.params)
  File "/usr/local/lib/python3.10/dist-packages/transformers/pipelines/base.py", line 1028, in forward
    model_outputs = self._forward(model_inputs, **forward_params)
  File "/usr/local/lib/python3.10/dist-packages/whisperx/asr.py", line 279, in _forward
    outputs = self.model.generate_segment_batched(model_inputs['inputs'], self.tokenizer, self.options)
  File "/usr/local/lib/python3.10/dist-packages/whisperx/asr.py", line 165, in generate_segment_batched
    result = self.model.generate(
TypeError: generate(): incompatible function arguments. The following argument types are supported:
    1. (self: ctranslate2._ext.Whisper, features: ctranslate2._ext.StorageView, prompts: Union[List[List[str]], List[List[int]]], *, asynchronous: bool = False, beam_size: int = 5, patience: float = 1, num_hypotheses: int = 1, length_penalty: float = 1, repetition_penalty: float = 1, no_repeat_ngram_size: int = 0, max_length: int = 448, return_scores: bool = False, return_no_speech_prob: bool = False, max_initial_timestamp_index: int = 50, suppress_blank: bool = True, suppress_tokens: Optional[List[int]] = [-1], sampling_topk: int = 1, sampling_temperature: float = 1) -> Union[List[ctranslate2._ext.WhisperGenerationResult], List[ctranslate2._ext.WhisperGenerationResultAsync]]

Invoked with: <ctranslate2._ext.Whisper object at 0x7ca0d5158b70>, <ctranslate2._ext.StorageView object at 0x7ca0d51ab8f0>, [[50258, 50262, 50359, 50363], [50258, 50262, 50359, 50363], [50258, 50262, 50359, 50363], [50258, 50262, 50359, 50363], [50258, 50262, 50359, 50363], [50258, 50262, 50359, 50363], [50258, 50262, 50359, 50363], [50258, 50262, 50359, 50363]]; kwargs: length_penalty=1.0, max_length=448, return_scores=True, return_no_speech_prob=True, suppress_blank=True, suppress_tokens=[-1], beam_size=5, patience=None
`

**Comment by m-bain** [comment]
thanks I reverted this PR, it caused breaking
