### ISSUE TITLE
Crashed by ZeroDivisionError when set "--print_progress True"

### ISSUE THREAD

**Issue by antiPoP** [m-bain/whisperX#502]
Hi, I'm still experiencing #477:
```
>>Performing alignment...
Traceback (most recent call last):
  File "/home/code/apps/miniconda3/envs/whisperx/bin/whisperx", line 8, in <module>
    sys.exit(cli())
  File "/home/code/apps/miniconda3/envs/whisperx/lib/python3.10/site-packages/whisperx/transcribe.py", line 195, in cli
    result = align(result["segments"], align_model, align_metadata, input_audio, device, interpolate_method=interpolate_method, return_char_alignments=return_char_alignments, print_progress=print_progress)
  File "/home/code/apps/miniconda3/envs/whisperx/lib/python3.10/site-packages/whisperx/alignment.py", line 126, in align
    base_progress = ((sdx + 1) / total_segments) * 100
ZeroDivisionError: division by zero
```

**Comment by VatinaCharo** [comment]
you can try to update your whisperx by:
`pip install git+https://github.com/m-bain/whisperx.git --upgrade`
Bug has been fixed in Sep 27.

**Comment by antiPoP** [comment]
It happens with the latest version. `total_segments` can be zero, what is not checked:

https://github.com/m-bain/whisperX/blob/4cdce3b927a4dcf8eea1da2b68e36290095c4812/whisperx/alignment.py#L121-L128

**Comment by saveli** [comment]
Can confirm, still same error on 16th Oct.

**Comment by Barabazs** [comment]
For anyone running into this issue:
Please provide a sample audio and script/command to reproduce this bug

**Comment by antiPoP** [comment]
Seems fixed in the latest versions.
