### ISSUE TITLE
whisperx: error: unrecognized arguments: --vad_filter --parallel_bs 16

### ISSUE THREAD

**Issue by janderez** [m-bain/whisperX#59]
Hi,
I get this error message when trying to run whisperx with the latest features (VAD and parallel processing).
I have already upgraded to the latest version with all the requirements being satisfied...
Any clue on what it is missing/wrong in my installation?
Thanks&Regards,

**Comment by janderez** [comment]
Yes, it seems something is wrong to do the upgrade, though I still don't know if it has to do with my installation or with whisperx y/o pip:

!pip install git+https://github.com/m-bain/whisperx.git --upgrade --verbose

Using pip 21.1.3 from /usr/local/lib/python3.7/dist-packages/pip (python 3.7)
Value for scheme.platlib does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: /usr/local/lib/python3.7/dist-packages
sysconfig: /usr/lib/python3.7/site-packages
Value for scheme.purelib does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: /usr/local/lib/python3.7/dist-packages
sysconfig: /usr/lib/python3.7/site-packages
Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: /usr/local/include/python3.7/UNKNOWN
sysconfig: /usr/include/python3.7m/UNKNOWN
Value for scheme.scripts does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: /usr/local/bin
sysconfig: /usr/bin
Value for scheme.data does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: /usr/local
sysconfig: /usr
Additional context:
user = False
home = None
root = None
prefix = None
Non-user install because site-packages writeable
Created temporary directory: /tmp/pip-ephem-wheel-cache-mpwa59r2
Created temporary directory: /tmp/pip-req-tracker-8vi0634l
Initialized build tracking at /tmp/pip-req-tracker-8vi0634l
Created build tracker: /tmp/pip-req-tracker-8vi0634l
Entered build tracker: /tmp/pip-req-tracker-8vi0634l
Created temporary directory: /tmp/pip-install-n0bpfmvu
Collecting git+https://github.com/m-bain/whisperx.git
  Created temporary directory: /tmp/pip-req-build-1ubzv1wf
  Cloning https://github.com/m-bain/whisperx.git to /tmp/pip-req-build-1ubzv1wf
  Running command git clone -q https://github.com/m-bain/whisperx.git /tmp/pip-req-build-1ubzv1wf
  Added git+https://github.com/m-bain/whisperx.git to build tracker '/tmp/pip-req-tracker-8vi0634l'
    Running setup.py (path:/tmp/pip-req-build-1ubzv1wf/setup.py) egg_info for package from git+https://github.com/m-bain/whisperx.git
    Created temporary directory: /tmp/pip-pip-egg-info-lfpf4rgb
    Running command python setup.py egg_info
    running egg_info
    creating /tmp/pip-pip-egg-info-lfpf4rgb/whisperx.egg-info
    writing /tmp/pip-pip-egg-info-lfpf4rgb/whisperx.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-pip-egg-info-lfpf4rgb/whisperx.egg-info/dependency_links.txt
    writing entry points to /tmp/pip-pip-egg-info-lfpf4rgb/whisperx.egg-info/entry_points.txt
    writing requirements to /tmp/pip-pip-egg-info-lfpf4rgb/whisperx.egg-info/requires.txt
    writing top-level names to /tmp/pip-pip-egg-info-lfpf4rgb/whisperx.egg-info/top_level.txt
    writing manifest file '/tmp/pip-pip-egg-info-lfpf4rgb/whisperx.egg-info/SOURCES.txt'
    /usr/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'readme'
      warnings.warn(msg)
    file whisperx.py (for module whisperx) not found
    reading manifest template 'MANIFEST.in'
    adding license file 'LICENSE'
    writing manifest file '/tmp/pip-pip-egg-info-lfpf4rgb/whisperx.egg-info/SOURCES.txt'
  Source in /tmp/pip-req-build-1ubzv1wf has version 1.0, which satisfies requirement whisperx==1.0 from git+https://github.com/m-bain/whisperx.git
  Removed whisperx==1.0 from git+https://github.com/m-bain/whisperx.git from build tracker '/tmp/pip-req-tracker-8vi0634l'

**Comment by janderez** [comment]
I have uninstalled whisperx and installed it again. Now I don't get the error of "unrecognized arguments" but a new one instead, regardless of trying to use the new arguments or not:

Traceback (most recent call last):
  File "/usr/local/bin/whisperx", line 5, in <module>
    from whisperx.transcribe import cli
  File "/usr/local/lib/python3.7/dist-packages/whisperx/__init__.py", line 13, in <module>
    from .model import Whisper, ModelDimensions
  File "/usr/local/lib/python3.7/dist-packages/whisperx/model.py", line 11, in <module>
    from .transcribe import transcribe as transcribe_function
  File "/usr/local/lib/python3.7/dist-packages/whisperx/transcribe.py", line 10, in <module>
    from .alignment import load_align_model, align, get_trellis, backtrack, merge_repeats, merge_words
  File "/usr/local/lib/python3.7/dist-packages/whisperx/alignment.py", line 248
    seg_lens_cumsum = [v := v + n for n in seg_lens]
                         ^
SyntaxError: invalid syntax

**Comment by janderez** [comment]
The previous issues had to do with the version of python (3.7), I have upgraded to version 3.8.16 and now everything works fine
