### ISSUE TITLE
float16 on Maxwell (M1200)?

### ISSUE THREAD

**Issue by bugsyb** [m-bain/whisperX#612]
Trying to run WhisperX on Nvidia M1200 gets below error. Web suggests that Maxwell supports float16, hence unsure why it bombs out.

It works with float32, though this is not desired. 

Running whisper.cc doesn't suffer from this issue and didn't need to force float32.

```
Traceback (most recent call last):
  File "/venv/bin/whisperx", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/venv/lib/python3.11/site-packages/whisperx/transcribe.py", line 169, in cli
    model = load_model(model_name, device=device, device_index=device_index, compute_type=compute_type, language=args['language'], asr_options=asr_options, vad_options={"vad_onset": vad_onset, "vad_offset": vad_offset}, task=task, threads=faster_whisper_threads)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/whisperx/asr.py", line 287, in load_model
    model = model or WhisperModel(whisper_arch,
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/faster_whisper/transcribe.py", line 130, in __init__
    self.model = ctranslate2.models.Whisper(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: **Requested float16 compute type, but the target device or backend do not support efficient float16 computation.**
```

**Comment by Barabazs** [comment]
Closing this issue due to inactivity and its age.

If this issue persists, please feel free to reopen it.
