### ISSUE TITLE
Upgrade to pyannote 3.1.0 breaks whisperx

### ISSUE THREAD

**Issue by Triquetra** [m-bain/whisperX#633]
Upgrading whisperX via the recommended: pip install git+https://github.com/m-bain/whisperx.git --upgrade

Produces errors about unresolved conflicts between the installed version of pyannote (3.1.0) and what whisperx requires (3.0.1).

Attempting to run whisperx after upgrade produces the following:

```
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\pkg_resources\__init__.py", line 631, in _build_master
    ws.require(__requires__)
  File "C:\Python310\lib\site-packages\pkg_resources\__init__.py", line 968, in require
    needed = self.resolve(parse_requirements(requirements))
  File "C:\Python310\lib\site-packages\pkg_resources\__init__.py", line 829, in resolve
    dist = self._resolve_dist(
  File "C:\Python310\lib\site-packages\pkg_resources\__init__.py", line 875, in _resolve_dist
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pyannote.audio 3.1.0 (c:\python310\lib\site-packages), Requirement.parse('pyannote.audio==3.0.1'), {'whisperx'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "\\?\C:\Python310\Scripts\whisperx-script.py", line 33, in <module>
    sys.exit(load_entry_point('whisperx==3.1.1', 'console_scripts', 'whisperx')())
  File "\\?\C:\Python310\Scripts\whisperx-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "C:\Python310\lib\importlib\metadata\__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "C:\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Python310\lib\site-packages\whisperx\__init__.py", line 1, in <module>
    from .transcribe import load_model
  File "C:\Python310\lib\site-packages\whisperx\transcribe.py", line 10, in <module>
    from .asr import load_model
  File "C:\Python310\lib\site-packages\whisperx\asr.py", line 5, in <module>
    import ctranslate2
  File "C:\Python310\lib\site-packages\ctranslate2\__init__.py", line 8, in <module>
    import pkg_resources
  File "C:\Python310\lib\site-packages\pkg_resources\__init__.py", line 3328, in <module>
    def _initialize_master_working_set():
  File "C:\Python310\lib\site-packages\pkg_resources\__init__.py", line 3302, in _call_aside
    f(*args, **kwargs)
  File "C:\Python310\lib\site-packages\pkg_resources\__init__.py", line 3340, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "C:\Python310\lib\site-packages\pkg_resources\__init__.py", line 633, in _build_master
    return cls._build_from_requirements(__requires__)
  File "C:\Python310\lib\site-packages\pkg_resources\__init__.py", line 646, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "C:\Python310\lib\site-packages\pkg_resources\__init__.py", line 829, in resolve
    dist = self._resolve_dist(
  File "C:\Python310\lib\site-packages\pkg_resources\__init__.py", line 870, in _resolve_dist
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pyannote.audio==3.0.1' distribution was not found and is required by whisperxTraceback (most recent call last):
  File "C:\Python310\lib\site-packages\pkg_resources\__init__.py", line 631, in _build_master
    ws.require(__requires__)
  File "C:\Python310\lib\site-packages\pkg_resources\__init__.py", line 968, in require
    needed = self.resolve(parse_requirements(requirements))
  File "C:\Python310\lib\site-packages\pkg_resources\__init__.py", line 829, in resolve
    dist = self._resolve_dist(
  File "C:\Python310\lib\site-packages\pkg_resources\__init__.py", line 875, in _resolve_dist
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pyannote.audio 3.1.0 (c:\python310\lib\site-packages), Requirement.parse('pyannote.audio==3.0.1'), {'whisperx'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "\\?\C:\Python310\Scripts\whisperx-script.py", line 33, in <module>
    sys.exit(load_entry_point('whisperx==3.1.1', 'console_scripts', 'whisperx')())
  File "\\?\C:\Python310\Scripts\whisperx-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "C:\Python310\lib\importlib\metadata\__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "C:\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Python310\lib\site-packages\whisperx\__init__.py", line 1, in <module>
    from .transcribe import load_model
  File "C:\Python310\lib\site-packages\whisperx\transcribe.py", line 10, in <module>
    from .asr import load_model
  File "C:\Python310\lib\site-packages\whisperx\asr.py", line 5, in <module>
    import ctranslate2
  File "C:\Python310\lib\site-packages\ctranslate2\__init__.py", line 8, in <module>
    import pkg_resources
  File "C:\Python310\lib\site-packages\pkg_resources\__init__.py", line 3328, in <module>
    def _initialize_master_working_set():
  File "C:\Python310\lib\site-packages\pkg_resources\__init__.py", line 3302, in _call_aside
    f(*args, **kwargs)
  File "C:\Python310\lib\site-packages\pkg_resources\__init__.py", line 3340, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "C:\Python310\lib\site-packages\pkg_resources\__init__.py", line 633, in _build_master
    return cls._build_from_requirements(__requires__)
  File "C:\Python310\lib\site-packages\pkg_resources\__init__.py", line 646, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "C:\Python310\lib\site-packages\pkg_resources\__init__.py", line 829, in resolve
    dist = self._resolve_dist(
  File "C:\Python310\lib\site-packages\pkg_resources\__init__.py", line 870, in _resolve_dist
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pyannote.audio==3.0.1' distribution was not found and is required by whisperx
```

**Comment by Triquetra** [comment]
```
pip install --upgrade --force-reinstall --no-deps git+https://github.com/m-bain/whisperx.git
```
seems to have solved the problem for me
