### ISSUE TITLE
ImportError: cannot import name 'wraps' from partially initialized module 'functools'

### ISSUE THREAD

**Issue by afsara-ben** [m-bain/whisperX#682]
While debugging in Pytorch i get the error

Error processing line 1 of /Users/afsarabenazir/Downloads/speech_projects/whisperX-main/lib/python3.10/site-packages/_virtualenv.pth:

Fatal Python error: init_import_site: Failed to import the site module
Python runtime state: initialized
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site.py", line 186, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
  File "/Users/afsarabenazir/Downloads/speech_projects/whisperX-main/lib/python3.10/site-packages/_virtualenv.py", line 40, in <module>
    from functools import partial
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/functools.py", line 22, in <module>
    from types import GenericAlias
  File "/Users/afsarabenazir/Downloads/speech_projects/whisperX-main/whisperx/types.py", line 1, in <module>
    from typing import TypedDict, Optional, List
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/typing.py", line 25, in <module>
    import contextlib
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/contextlib.py", line 6, in <module>
    from functools import wraps
ImportError: cannot import name 'wraps' from partially initialized module 'functools' (most likely due to a circular import) (/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/functools.py)
 
Any solution to this?

**Comment by bear-boy** [comment]
Same error.
Just rename types.py file to something like xxx_types.py, it works for me.
