### ISSUE TITLE
[Bug:] (Colab) whisperx cli tool - PackageNotFoundError: whisperx

### ISSUE THREAD

**Issue by ClashSAN** [m-bain/whisperX#70]
!cd whisperX && pip install -e .
```
Installing collected packages: whisperx
  Running setup.py develop for whisperx
Successfully installed whisperx
```
>!whisperx test.wav

```
Traceback (most recent call last):
  File "/usr/bin/whisperx", line 33, in <module>
    sys.exit(load_entry_point('whisperx', 'console_scripts', 'whisperx')())
  File "/usr/bin/whisperx", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.9/importlib/metadata.py", line 542, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.9/importlib/metadata.py", line 196, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: whisperx
```

after setup installation, does it need to be restarted?

**Comment by ClashSAN** [comment]
my mistake, was trying to install a newer python version beforehand, which messed things up.
