### ISSUE TITLE
Suddenly stopped working

### ISSUE THREAD

**Issue by fznx922** [m-bain/whisperX#702]
good morning, been running whisperx via subtitle edit, had it setup for a while now and was working great, now unfortunately it seems something had changed, now im unable to get it to run, it runs for maybe 10 secconds, says no text and asks if i want to see logs, in the logs i get an output like this
```

Date: 02/17/2024 10:41:31
SE: 4.0.3.127 - Microsoft Windows NT 10.0.22631.0 - 64-bit
Message: Calling whisper (WhisperX) with : C:\Users\fznx\anaconda3\envs\wx\Scripts\whisperx.exe --language ja --model "large-v3" --task translate  "C:\Users\fznx\AppData\Local\Temp\d9971be5-20be-40cc-b20e-bbd1187e50f5.wav"
Traceback (most recent call last):

OSError: [WinError 127] The specified procedure could not be found

self._handle = _dlopen(self._name, mode)

File "C:\Users\fznx\anaconda3\envs\wx\lib\ctypes\__init__.py", line 374, in __init__

ctypes.CDLL(path)

File "C:\Users\fznx\anaconda3\envs\wx\lib\site-packages\torch\_ops.py", line 852, in load_library

torch.ops.load_library(path)

File "C:\Users\fznx\AppData\Roaming\Python\Python310\site-packages\torchaudio\_extension\utils.py", line 60, in _load_lib

_load_lib("libtorchaudio")

File "C:\Users\fznx\AppData\Roaming\Python\Python310\site-packages\torchaudio\_extension\__init__.py", line 38, in <module>

from . import _extension  # noqa  # usort: skip

File "C:\Users\fznx\AppData\Roaming\Python\Python310\site-packages\torchaudio\__init__.py", line 2, in <module>

import torchaudio

File "C:\Users\fznx\anaconda3\envs\wx\lib\site-packages\whisperx\alignment.py", line 11, in <module>

from .alignment import align, load_align_model

File "C:\Users\fznx\anaconda3\envs\wx\lib\site-packages\whisperx\transcribe.py", line 9, in <module>

from .transcribe import load_model

File "C:\Users\fznx\anaconda3\envs\wx\lib\site-packages\whisperx\__init__.py", line 1, in <module>

File "C:\Users\fznx\anaconda3\envs\wx\Scripts\whisperx.exe\__main__.py", line 4, in <module>

exec(code, run_globals)

File "C:\Users\fznx\anaconda3\envs\wx\lib\runpy.py", line 86, in _run_code

return _run_code(code, main_globals, None,

File "C:\Users\fznx\anaconda3\envs\wx\lib\runpy.py", line 196, in _run_module_as_main
Calling whisper WhisperX done in 00:00:05.2068212
Loading result from STDOUT
```

if anyone had any suggestions or had this error before and fixed, would be much appreciated, 

things ive tried are deleting and reinstalling environment, including fresh pull of whisperx, reinstalling cuda drivers, installing different versions of pytorch and such, still no joy 

if any more information is needed please let me know 

thank you :)

**Comment by Barabazs** [comment]
Please don't open issues for other software here. You will need to request support from Subtitle Edit.
