### ISSUE TITLE
Whisper-X is completely broken for me after the new update.

### ISSUE THREAD

**Issue by OPPEYRADY** [m-bain/whisperX#719]
```
Traceback (most recent call last):
  File "C:\Users\skipz\OneDrive\Desktop\Celeste-AI-Filesystem\AMADEUS - CURRENT\SYSTEM\GENERAL\connection_handler.py", line 223, in run
    function_caller = self.function.__call__(reconstructed_information)
  File "C:\Users\skipz\OneDrive\Desktop\Celeste-AI-Filesystem\AMADEUS - CURRENT\SYSTEM\CORE\ServiceHandler.py", line 361, in __call__
    transcription, language = self.transcribe_audio_buffer(audio_float_32)
  File "C:\Users\skipz\OneDrive\Desktop\Celeste-AI-Filesystem\AMADEUS - CURRENT\SYSTEM\CORE\ServiceHandler.py", line 232, in transcribe_audio_buffer
    transcription, language = WhisperService.transcription(audio_buffer)
  File "C:\Users\skipz\OneDrive\Desktop\Celeste-AI-Filesystem\AMADEUS - CURRENT\SYSTEM\CORE\WHISPERX\WHSP.py", line 48, in transcription
    result = self.model.transcribe(audio, batch_size=self.batch_size)
  File "C:\Users\skipz\miniconda3\envs\BOTSERVICE\lib\site-packages\whisperx\asr.py", line 218, in transcribe
    for idx, out in enumerate(self.__call__(data(audio, vad_segments), batch_size=batch_size, num_workers=num_workers)):
  File "C:\Users\skipz\miniconda3\envs\BOTSERVICE\lib\site-packages\transformers\pipelines\pt_utils.py", line 124, in __next__
    item = next(self.iterator)
  File "C:\Users\skipz\miniconda3\envs\BOTSERVICE\lib\site-packages\transformers\pipelines\pt_utils.py", line 125, in __next__
    processed = self.infer(item, **self.params)
  File "C:\Users\skipz\miniconda3\envs\BOTSERVICE\lib\site-packages\transformers\pipelines\base.py", line 1046, in forward
    model_outputs = self._forward(model_inputs, **forward_params)
  File "C:\Users\skipz\miniconda3\envs\BOTSERVICE\lib\site-packages\whisperx\asr.py", line 152, in _forward
    outputs = self.model.generate_segment_batched(model_inputs['inputs'], self.tokenizer, self.options)
  File "C:\Users\skipz\miniconda3\envs\BOTSERVICE\lib\site-packages\whisperx\asr.py", line 47, in generate_segment_batched
    encoder_output = self.encode(features)
  File "C:\Users\skipz\miniconda3\envs\BOTSERVICE\lib\site-packages\whisperx\asr.py", line 86, in encode
    return self.model.encode(features, to_cpu=to_cpu)
RuntimeError: Library cublas64_12.dll is not found or cannot be loaded
```

For some reason, after doing a reinstall on my environment, whisper-x is now completely borked and crashes the moment I try to infer to it, it has never done this before and only started happening after I did a reinstall today with my custom auto installer.

**Comment by OPPEYRADY** [comment]
Made a temp fix, by renaming the file "cublas64_11" to cublas64_12".

**Comment by StDensity** [comment]
any fix other than rename?

**Comment by deep-pipeline** [comment]
@OPPEYRADY have you managed to find a solution? If so, could you note it and close this issue please (I'm just trying to find ways to reduce live number of open issues to assist developer bandwidth). Thanks.

**Comment by OPPEYRADY** [comment]
@deep-pipeline 
IIRC ctranslate==3.24.0 may have helped, but that was the only solution I found thus far besides renaming the file.

**Comment by OPPEYRADY** [comment]
unfortunately this needs someone to fix this as its pretty critical but i'm not sure of any real official fixes that can be made besides my hacky methods.

**Comment by eashanchawla** [comment]
Maybe we can pull an older version of the whisperx repository since this one has a requirement for faster-whisper 1 which inevitably forces us to pull a version of ctranslate that is > 4, which needs CUDA 12. This is rough because Azure ML (where my whisperx was running, doesn't support base images with cuda 12 yet). Another option could be to also use an older base image in my dockerfile and try to update CUDA from there (which can be problematic in itself).
