### ISSUE TITLE
An error will be reported if there is only one sentence : KeyError: 'level_1'

### ISSUE THREAD

**Issue by djkcyl** [m-bain/whisperX#72]
If the output of whisper contains only one sentence, the alignment will not work

```
(v2a) azure@CUDA:~/v2d$ python main.py 
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
cutting 0 ...
[00:00.000 --> 00:06.000] 还没到的樱花季 还没用的折响机
[{'id': 0, 'seek': 0, 'start': 0.0, 'end': 6.0, 'text': '还没到的樱花季 还没用的折响机', 'tokens': [50364, 7824, 4913, 4511, 1546, 162, 104, 119, 20127, 8052, 96, 220, 7824, 4913, 9254, 1546, 7235, 246, 13665, 123, 17543, 50664], 'temperature': 0.0, 'avg_logprob': -0.37327724954356317, 'compression_ratio': 0.8775510204081632, 'no_speech_prob': 0.637145459651947}]
Failed to align segment (""): no characters in this segment found in model dictionary, resorting to original...
/home/azure/miniconda3/envs/v2a/lib/python3.10/site-packages/whisperx/alignment.py:302: FutureWarning: Not prepending group keys to the result index of transform-like apply. In the future, the group keys will be included in the index, regardless of whether the applied function returns a like-indexed object.
To preserve the previous behavior, use

        >>> .groupby(..., group_keys=False)

To adopt the future behavior and silence this warning, use 

        >>> .groupby(..., group_keys=True)
  char_segments_arr = per_seg_grp.apply(lambda x: x.reset_index(drop = True)).reset_index()
Traceback (most recent call last):
  File "/home/azure/miniconda3/envs/v2a/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3802, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5745, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5753, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'level_1'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/azure/v2d/main.py", line 42, in <module>
    align_result = whisperx.align(
  File "/home/azure/miniconda3/envs/v2a/lib/python3.10/site-packages/whisperx/alignment.py", line 392, in align
    cseg['segment-text-start'] = cseg['level_1']
  File "/home/azure/miniconda3/envs/v2a/lib/python3.10/site-packages/pandas/core/frame.py", line 3807, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/azure/miniconda3/envs/v2a/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3804, in get_loc
    raise KeyError(key) from err
KeyError: 'level_1'
(v2a) azure@CUDA:~/v2d$
```

```python

audio_path = Path("test.wav")
model_name = "large"
device = "cuda"
language = "zh"
model = whisperx.load_model(model_name, device=device, download_root="models")
align_model, align_metadata = whisperx.load_align_model(
    language_code="zh",
    device=device,
    model_name="wbbbbb/wav2vec2-large-chinese-zh-cn",
)

result = model.transcribe(str(cut_file), language=language, verbose=True)
print(result["segments"])
align_result = whisperx.align(
    result["segments"], align_model, align_metadata, str(cut_file), device
)
```

**Comment by LyWangPX** [comment]
I believe you do not need char-level details of time stamps.
Then, comment out [these lines](https://github.com/m-bain/whisperX/blob/main/whisperx/alignment.py#L391-L405) will help.

**Comment by djkcyl** [comment]
> I believe you do not need char-level details of time stamps. Then, comment out [these lines](https://github.com/m-bain/whisperX/blob/main/whisperx/alignment.py#L391-L405) will help.

Okay, I'll try it.

**Comment by LyWangPX** [comment]
The solution I mentioned might be too brutal.
It is better to just remove anything involving `cseg`, since you might still want to keep `aligned_segments.append`.

**Comment by Jxspa** [comment]
I have the same problem trying to transcribe short files. The above suggestion results in an empty output file, with this warning -
```
Performing transcription...
[00:00.000 --> 00:04.080] I'm an animal person.
Performing alignment...
C:\Users\X\.pyenv\pyenv-win\versions\3.10.5\lib\site-packages\whisperx\alignment.py:302: FutureWarning: Not prepending group keys to the result index of transform-like apply. In the future, the group keys will be included in the index, regardless of whether the applied function returns a like-indexed object.
To preserve the previous behavior, use

        >>> .groupby(..., group_keys=False)

To adopt the future behavior and silence this warning, use

        >>> .groupby(..., group_keys=True)
  char_segments_arr = per_seg_grp.apply(lambda x: x.reset_index(drop = True)).reset_index()
```

**Comment by LyWangPX** [comment]
The warning is a `FutureWarning` which can be ignored safely by `warnings.simplefilter('ignore', FutureWarning)`.
The reason why your file is empty must be caused by something else.
I think you should use the python interface for further debugging.
For example, you can compare what have you got from whisper model and align like this:
```python
import whisperx
import os
import pandas as pd
import warnings
warnings.simplefilter('ignore', FutureWarning)
device = "cuda" 

model = whisperx.load_model("large-v2", device)
model_a, metadata = whisperx.load_align_model(language_code='en',device=device, model_name="facebook/wav2vec2-large-960h-lv60-self")
audio_file = "your audio file path"
whisper_result = model.transcribe(audio_file)
result_aligned = whisperx.align(whisper_result["segments"], model_a, metadata, audio_file, device)
```

**Comment by LyWangPX** [comment]
BTW, you may want to see [this PR](https://github.com/m-bain/whisperX/pull/74).

**Comment by Jxspa** [comment]
> BTW, you may want to see [this PR](https://github.com/m-bain/whisperX/pull/74).

This works for me. Thanks!

**Comment by m-bain** [comment]
this should be gone now
