### ISSUE TITLE
ValueError: 'waveform' must be provided as a (channel, time) torch Tensor.

### ISSUE THREAD

**Issue by asasas234** [m-bain/whisperX#752]
time whisperx kJ--A1UyQfg.mp4 --model=large-v3 --align_model WAV2VEC2_ASR_LARGE_LV60K_960H  --compute_type int8 --language en  --output_format json

```
Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.0.4. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file ../../../.cache/torch/whisperx-vad-segmentation.bin`
Model was trained with pyannote.audio 0.0.1, yours is 3.1.1. Bad things might happen unless you revert pyannote.audio to 0.x.
Model was trained with torch 1.10.0+cu102, yours is 2.0.0. Bad things might happen unless you revert torch to 1.x.
>>Performing transcription...
Traceback (most recent call last):
  File "/Users/lizhibo/miniconda3/envs/whisperx/bin/whisperx", line 8, in <module>
    sys.exit(cli())
  File "/Users/lizhibo/miniconda3/envs/whisperx/lib/python3.10/site-packages/whisperx/transcribe.py", line 176, in cli
    result = model.transcribe(audio, batch_size=batch_size, chunk_size=chunk_size, print_progress=print_progress)
  File "/Users/lizhibo/miniconda3/envs/whisperx/lib/python3.10/site-packages/whisperx/asr.py", line 186, in transcribe
    vad_segments = self.vad_model({"waveform": torch.from_numpy(audio).unsqueeze(0), "sample_rate": SAMPLE_RATE})
  File "/Users/lizhibo/miniconda3/envs/whisperx/lib/python3.10/site-packages/pyannote/audio/core/pipeline.py", line 320, in __call__
    file = Audio.validate_file(file)
  File "/Users/lizhibo/miniconda3/envs/whisperx/lib/python3.10/site-packages/pyannote/audio/core/io.py", line 155, in validate_file
    raise ValueError(
ValueError: 'waveform' must be provided as a (channel, time) torch Tensor.
whisperx kJ--A1UyQfg.mp4 --model=large-v3 --align_model  --compute_type int8   5.87s user 3.88s system 118% cpu 8.256 total
```

@m-bain When I was using whisperx, I encountered this problem. How can I solve it?

**Comment by jferments** [comment]
I am also experiencing the same issue and am curious what I need to do to resolve.

**Comment by asasas234** [comment]
@jferments, I recently discovered the reason for this issue, which is that some of the videos being transcribed do not have any audio. You can also check if it's due to the same reason.

**Comment by jferments** [comment]
Thanks, but I am attempting to transcribe from an ndarray containing audio recorded with sounddevice library. The audio is there, and I can play it back with sd.play() ... but when I attempt to pass it to whisper_model.transcribe() that's when I get the error. Here is my code:

`import sounddevice as sd
import whisperx

INPUT_DEVICE = 4
OUTPUT_DEVICE = 9
CHANNELS = 2              # Number of audio channels (mono)
SAMPLE_RATE = 48000              # Sample rate (samples per second)
DURATION = 5        # Duration of recording

WHISPERX_DEVICE = "cuda"
WHISPERX_COMPUTE_TYPE = "float16" # change to "int8" if low on GPU mem (may reduce accuracy)
WHISPERX_MODEL_DIR = "./models/whisper/"
WHISPERX_PRINT_PROGRESS = True
WHISPERX_BATCH_SIZE = 1024

whisper_model = whisperx.load_model("medium", WHISPERX_DEVICE, compute_type=WHISPERX_COMPUTE_TYPE, download_root=WHISPERX_MODEL_DIR)

sd.default.device = 4, 9
sd.default.samplerate = SAMPLE_RATE

audio_data = sd.rec(int(DURATION * SAMPLE_RATE), samplerate=SAMPLE_RATE, channels=CHANNELS)

print(audio_data, type(audio_data), audio_data.shape)`

Gives: 

`[[0.00262451 0.00262451]
 [0.06124878 0.06124878]
 [0.01635742 0.01635742]
 ...
 [0.0196228  0.0196228 ]
 [0.0085144  0.0085144 ]
 [0.02905273 0.02905273]] <class 'numpy.ndarray'> (240000, 2)`

When I play it with sd.play() it sounds fine.

But then if I run this code, I get the error:

`result = whisper_model.transcribe(audio_data, chunk_size=DURATION, print_progress=WHISPERX_PRINT_PROGRESS)
print(result["segments"]) # before alignment
model_a, metadata = whisperx.load_align_model(language_code=result["language"], device=WHISPERX_DEVICE)
result = whisperx.align(result["segments"], model_a, metadata, audio_data, WHISPERX_DEVICE, return_char_alignments=False)

print(result["segments"]) # after alignment
`

Gives:

`---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[12], line 2
      1 start_time = time.time()
----> 2 result = whisper_model.transcribe(audio_data, chunk_size=DURATION, print_progress=WHISPERX_PRINT_PROGRESS)
      3 print(result["segments"]) # before alignment
      5 # 2. Align whisper output

File [~/code/oassistant/oassist-venv/lib/python3.12/site-packages/whisperx/asr.py:186](http://localhost:8888/lab/tree/oassist-venv/lib/python3.12/site-packages/whisperx/asr.py#line=185), in FasterWhisperPipeline.transcribe(self, audio, batch_size, num_workers, language, task, chunk_size, print_progress, combined_progress)
    183         # print(f2-f1)
    184         yield {'inputs': audio[f1:f2]}
--> 186 vad_segments = self.vad_model({"waveform": torch.from_numpy(audio).unsqueeze(0), "sample_rate": SAMPLE_RATE})
    187 vad_segments = merge_chunks(
    188     vad_segments,
    189     chunk_size,
    190     onset=self._vad_params["vad_onset"],
    191     offset=self._vad_params["vad_offset"],
    192 )
    193 if self.tokenizer is None:

File [~/code/oassistant/oassist-venv/lib/python3.12/site-packages/pyannote/audio/core/pipeline.py:320](http://localhost:8888/lab/tree/oassist-venv/lib/python3.12/site-packages/pyannote/audio/core/pipeline.py#line=319), in Pipeline.__call__(self, file, **kwargs)
    311         raise RuntimeError(
    312             "A pipeline must be instantiated with `pipeline.instantiate(paramaters)` before it can be applied. "
    313             "Tried to use parameters provided by `pipeline.default_parameters()` but those are not compatible. "
    314         )
    316     warnings.warn(
    317         f"The pipeline has been automatically instantiated with {default_parameters}."
    318     )
--> 320 file = Audio.validate_file(file)
    322 if hasattr(self, "preprocessors"):
    323     file = ProtocolFile(file, lazy=self.preprocessors)

File [~/code/oassistant/oassist-venv/lib/python3.12/site-packages/pyannote/audio/core/io.py:155](http://localhost:8888/lab/tree/oassist-venv/lib/python3.12/site-packages/pyannote/audio/core/io.py#line=154), in Audio.validate_file(file)
    153 waveform: Union[np.ndarray, Tensor] = file["waveform"]
    154 if len(waveform.shape) != 2 or waveform.shape[0] > waveform.shape[1]:
--> 155     raise ValueError(
    156         "'waveform' must be provided as a (channel, time) torch Tensor."
    157     )
    159 sample_rate: int = file.get("sample_rate", None)
    160 if sample_rate is None:

ValueError: 'waveform' must be provided as a (channel, time) torch Tensor.---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[12], line 2
      1 start_time = time.time()
----> 2 result = whisper_model.transcribe(audio_data, chunk_size=DURATION, print_progress=WHISPERX_PRINT_PROGRESS)
      3 print(result["segments"]) # before alignment
      5 # 2. Align whisper output

File [~/code/oassistant/oassist-venv/lib/python3.12/site-packages/whisperx/asr.py:186](http://localhost:8888/lab/tree/oassist-venv/lib/python3.12/site-packages/whisperx/asr.py#line=185), in FasterWhisperPipeline.transcribe(self, audio, batch_size, num_workers, language, task, chunk_size, print_progress, combined_progress)
    183         # print(f2-f1)
    184         yield {'inputs': audio[f1:f2]}
--> 186 vad_segments = self.vad_model({"waveform": torch.from_numpy(audio).unsqueeze(0), "sample_rate": SAMPLE_RATE})
    187 vad_segments = merge_chunks(
    188     vad_segments,
    189     chunk_size,
    190     onset=self._vad_params["vad_onset"],
    191     offset=self._vad_params["vad_offset"],
    192 )
    193 if self.tokenizer is None:

File [~/code/oassistant/oassist-venv/lib/python3.12/site-packages/pyannote/audio/core/pipeline.py:320](http://localhost:8888/lab/tree/oassist-venv/lib/python3.12/site-packages/pyannote/audio/core/pipeline.py#line=319), in Pipeline.__call__(self, file, **kwargs)
    311         raise RuntimeError(
    312             "A pipeline must be instantiated with `pipeline.instantiate(paramaters)` before it can be applied. "
    313             "Tried to use parameters provided by `pipeline.default_parameters()` but those are not compatible. "
    314         )
    316     warnings.warn(
    317         f"The pipeline has been automatically instantiated with {default_parameters}."
    318     )
--> 320 file = Audio.validate_file(file)
    322 if hasattr(self, "preprocessors"):
    323     file = ProtocolFile(file, lazy=self.preprocessors)

File [~/code/oassistant/oassist-venv/lib/python3.12/site-packages/pyannote/audio/core/io.py:155](http://localhost:8888/lab/tree/oassist-venv/lib/python3.12/site-packages/pyannote/audio/core/io.py#line=154), in Audio.validate_file(file)
    153 waveform: Union[np.ndarray, Tensor] = file["waveform"]
    154 if len(waveform.shape) != 2 or waveform.shape[0] > waveform.shape[1]:
--> 155     raise ValueError(
    156         "'waveform' must be provided as a (channel, time) torch Tensor."
    157     )
    159 sample_rate: int = file.get("sample_rate", None)
    160 if sample_rate is None:

ValueError: 'waveform' must be provided as a (channel, time) torch Tensor.`

**Comment by keepitsane** [comment]
I am also experiencing this issue. It seems to happen when I try trim the audio first using FFMPEG, if I run the full audio I am not seeing any issues.

**Comment by Isuxiz** [comment]
Make sure your audio is mono, which means your ndarray is in 1D shape!
If not, use something like librosa to get mono audio first.
