### ISSUE TITLE
Cannot run with --diarize: error in numba decorators module

### ISSUE THREAD

**Issue by vrodriguezf** [m-bain/whisperX#78]
Hi,

When running whisperx with `--diarize`, I got this error:

```text
Traceback (most recent call last):
  File "/usr/local/bin/whisperx", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/dist-packages/whisperx/transcribe.py", line 653, in cli
    from pyannote.audio import Pipeline
  File "/usr/local/lib/python3.8/dist-packages/pyannote/audio/__init__.py", line 29, in <module>
    from .core.inference import Inference
  File "/usr/local/lib/python3.8/dist-packages/pyannote/audio/core/inference.py", line 35, in <module>
    from pyannote.audio.core.model import Model
  File "/usr/local/lib/python3.8/dist-packages/pyannote/audio/core/model.py", line 46, in <module>
    from pyannote.audio.core.task import Problem, Resolution, Specifications, Task
  File "/usr/local/lib/python3.8/dist-packages/pyannote/audio/core/task.py", line 45, in <module>
    from torch_audiomentations import Identity
  File "/usr/local/lib/python3.8/dist-packages/torch_audiomentations/__init__.py", line 1, in <module>
    from .augmentations.background_noise import AddBackgroundNoise
  File "/usr/local/lib/python3.8/dist-packages/torch_audiomentations/augmentations/background_noise.py", line 11, in <module>
    from ..utils.io import Audio
  File "/usr/local/lib/python3.8/dist-packages/torch_audiomentations/utils/io.py", line 5, in <module>
    import librosa
  File "/usr/local/lib/python3.8/dist-packages/librosa/__init__.py", line 209, in <module>
    from . import core
  File "/usr/local/lib/python3.8/dist-packages/librosa/core/__init__.py", line 5, in <module>
    from .convert import *  # pylint: disable=wildcard-import
  File "/usr/local/lib/python3.8/dist-packages/librosa/core/convert.py", line 7, in <module>
    from . import notation
  File "/usr/local/lib/python3.8/dist-packages/librosa/core/notation.py", line 8, in <module>
    from ..util.exceptions import ParameterError
  File "/usr/local/lib/python3.8/dist-packages/librosa/util/__init__.py", line 77, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "/usr/local/lib/python3.8/dist-packages/librosa/util/utils.py", line 9, in <module>
    import numba
  File "/usr/local/lib/python3.8/dist-packages/numba/__init__.py", line 42, in <module>
    from numba.np.ufunc import (vectorize, guvectorize, threading_layer,
  File "/usr/local/lib/python3.8/dist-packages/numba/np/ufunc/__init__.py", line 3, in <module>
    from numba.np.ufunc.decorators import Vectorize, GUVectorize, vectorize, guvectorize
  File "/usr/local/lib/python3.8/dist-packages/numba/np/ufunc/decorators.py", line 3, in <module>
    from numba.np.ufunc import _internal
SystemError: initialization of _internal failed without raising an exception
```

It seems to be something with numba's decorators module. My numba's version is `0.56.4`

Any idea?

**Comment by m-bain** [comment]
not sure here, can you retry installation with a fresh conda?
