### ISSUE TITLE
ValueError: Requested float16 compute type, but the target device or backend do not support efficient float16 computation

### ISSUE THREAD

**Issue by sugizo** [m-bain/whisperX#780]
**info**
- env : google colab
- os : ubuntu jammy x86_64
- python : 3.10.12

**steps**
```
pip install -U whisperx
!wget -c https://raw.githubusercontent.com/marl/pysox/master/tests/data/input.wav
!whisperx input.wav
```

**result**
```
2024-04-14 20:00:28.526425: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-04-14 20:00:28.526511: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-04-14 20:00:28.701606: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-04-14 20:00:32.429643: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
/usr/local/lib/python3.10/dist-packages/pyannote/audio/core/io.py:43: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
  torchaudio.set_audio_backend("soundfile")
vocabulary.txt:   0% 0.00/460k [00:00<?, ?B/s]
config.json: 100% 2.37k/2.37k [00:00<00:00, 8.51MB/s]

vocabulary.txt: 100% 460k/460k [00:00<00:00, 5.03MB/s]

tokenizer.json: 100% 2.20M/2.20M [00:00<00:00, 16.2MB/s]
model.bin: 100% 484M/484M [00:05<00:00, 83.0MB/s]
Traceback (most recent call last):
  File "/usr/local/bin/whisperx", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/dist-packages/whisperx/transcribe.py", line 170, in cli
    model = load_model(model_name, device=device, device_index=device_index, download_root=model_dir, compute_type=compute_type, language=args['language'], asr_options=asr_options, vad_options={"vad_onset": vad_onset, "vad_offset": vad_offset}, task=task, threads=faster_whisper_threads)
  File "/usr/local/lib/python3.10/dist-packages/whisperx/asr.py", line 289, in load_model
    model = model or WhisperModel(whisper_arch,
  File "/usr/local/lib/python3.10/dist-packages/faster_whisper/transcribe.py", line 133, in __init__
    self.model = ctranslate2.models.Whisper(
ValueError: Requested float16 compute type, but the target device or backend do not support efficient float16 computation.
```

best regards

**Comment by Basir-mahmood** [comment]
Also facing the same issue with colab.

**Comment by utility-aagrawal** [comment]
Are you using GPU or CPU? Try compute_type = "int8" with CPU or compute_type = "float16" with GPU.

**Comment by sugizo** [comment]
`!whisperx --compute_type 'int8' 'input.wav'`
solve the problem for CPU

thanks and best regards
