### ISSUE TITLE
Error While Using Machine With Only CPU (EC2 Instance)

### ISSUE THREAD

**Issue by anappdev** [m-bain/whisperX#800]
Trying to install on EC2 Amazon Linux, Number of vCPUs= 4, instance type = t2.xlarge

It gives error 
Traceback (most recent call last):
  File "/home/ec2-user/xwhisper.py", line 6, in <module>
    import whisperx
  File "/mnt/efs/fs1/ml/whisperx/whisperx/__init__.py", line 1, in <module>
    from .transcribe import load_model
  File "/mnt/efs/fs1/ml/whisperx/whisperx/transcribe.py", line 9, in <module>
    from .alignment import align, load_align_model
  File "/mnt/efs/fs1/ml/whisperx/whisperx/alignment.py", line 11, in <module>
    import torchaudio
  File "/home/ec2-user/.local/lib/python3.9/site-packages/torchaudio/__init__.py", line 1, in <module>
    from torchaudio import (  # noqa: F401
  File "/home/ec2-user/.local/lib/python3.9/site-packages/torchaudio/_extension/__init__.py", line 43, in <module>
    _load_lib("libtorchaudio")
  File "/home/ec2-user/.local/lib/python3.9/site-packages/torchaudio/_extension/utils.py", line 61, in _load_lib
    torch.ops.load_library(path)
  File "/home/ec2-user/.local/lib/python3.9/site-packages/torch/_ops.py", line 643, in load_library
    ctypes.CDLL(path)
  File "/usr/lib64/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libtorch_cuda.so: cannot open shared object file: No such file or directory

Any support for CPU only environment?

**Comment by SeeknnDestroy** [comment]
Hey @anappdev, 

Can you please try to use 'int8' as compute type?

'''python
import whisperx

model = whisperx.load_model(compute_type="int8")
'''

**Comment by anappdev** [comment]
> Hey @anappdev,
> 
> Can you please try to use `int8` as compute type?
> 
> ```python
> import whisperx
> 
> model = whisperx.load_model(compute_type="int8")
> ```

I used compute_type="int8", when I got that error
