### ISSUE TITLE
ValueError: Requested float16 compute type, but the target device or backend do not support efficient float16 computation.

### ISSUE THREAD

**Issue by S90pngprgm** [m-bain/whisperX#847]
I got the following error. Is there a way to fix it? My machine runs whisper without problem. So I think whisperx should also be adapted to machines without fp16.

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/bin/whisperx", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/whisperx/transcribe.py", line 170, in cli
    model = load_model(model_name, device=device, device_index=device_index, download_root=model_dir, compute_type=compute_type, language=args['language'], asr_options=asr_options, vad_options={"vad_onset": vad_onset, "vad_offset": vad_offset}, task=task, threads=faster_whisper_threads)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/whisperx/asr.py", line 289, in load_model
    model = model or WhisperModel(whisper_arch,
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/faster_whisper/transcribe.py", line 133, in __init__
    self.model = ctranslate2.models.Whisper(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Requested float16 compute type, but the target device or backend do not support efficient float16 computation.
```

**Comment by ibombonato** [comment]
Use `int8` for CPU or no `float16` when loading the model

```
device = "cuda" if torch.cuda.is_available() else "cpu"
compute_type = "float16" if torch.cuda.is_available() else "int8"

model = whisperx.load_model('tiny', device, 
                                compute_type=compute_type)
```

**Comment by hololeo** [comment]
in case someone else is searching for mac M1 silicon metal 16 gig macbook pro laptop. here is how to run it with the correct command line

whisperx --compute_type int8 examples/sample01.wav

**Comment by ilyazub** [comment]
Thank you @hololeo!

> whisperx --compute_type int8 examples/sample01.wav

This worked for me on Mac M3. Also, `float32` compute type worked:

```bash
whispers examples/sample01.wav --compute_type float32
```

**Comment by remic33** [comment]
When using int8 on Mac with m2, whisperx responds 
`TypeError: TranscriptionOptions.__new__() missing 3 required positional arguments: 'max_new_tokens', 'clip_timestamps', and 'hallucination_silence_threshold'`
