### ISSUE TITLE
Unable to run the whisperx with the installation steps provided in repository

### ISSUE THREAD

**Issue by GlitCher50** [m-bain/whisperX#850]
### Error
```bash
torchvision is not available - cannot save figures
No language specified, language will be first be detected for each audio file (increases inference time).
Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.3.3. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint C:\Users\nwert\.cache\torch\whisperx-vad-segmentation.bin`
Model was trained with pyannote.audio 0.0.1, yours is 3.1.1. Bad things might happen unless you revert pyannote.audio to 0.x.
Model was trained with torch 1.10.0+cu102, yours is 2.0.0. Bad things might happen unless you revert torch to 1.x.
>>Performing transcription...
Traceback (most recent call last):
  File "C:\Users\nwert\.conda\envs\whisperx\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\nwert\.conda\envs\whisperx\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\nwert\.conda\envs\whisperx\Scripts\whisperx.exe\__main__.py", line 7, in <module>
  File "C:\Users\nwert\.conda\envs\whisperx\lib\site-packages\whisperx\transcribe.py", line 176, in cli
    result = model.transcribe(audio, batch_size=batch_size, chunk_size=chunk_size, print_progress=print_progress)
  File "C:\Users\nwert\.conda\envs\whisperx\lib\site-packages\whisperx\asr.py", line 194, in transcribe
    language = language or self.detect_language(audio)
  File "C:\Users\nwert\.conda\envs\whisperx\lib\site-packages\whisperx\asr.py", line 252, in detect_language
    encoder_output = self.model.encode(segment)
  File "C:\Users\nwert\.conda\envs\whisperx\lib\site-packages\whisperx\asr.py", line 86, in encode
    return self.model.encode(features, to_cpu=to_cpu)
RuntimeError: Library cublas64_12.dll is not found or cannot be loaded
```

### Python version and packages installed with their version
Python 3.10.14
```bash
# Name                    Version                   Build  Channel
aiohappyeyeballs          2.3.4                    pypi_0    pypi
aiohttp                   3.10.1                   pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
alembic                   1.13.2                   pypi_0    pypi
antlr4-python3-runtime    4.9.3                    pypi_0    pypi
asteroid-filterbanks      0.4.0                    pypi_0    pypi
async-timeout             4.0.3                    pypi_0    pypi
attrs                     24.1.0                   pypi_0    pypi
audioread                 3.0.1                    pypi_0    pypi
av                        11.0.0                   pypi_0    pypi
blas                      1.0                         mkl
bzip2                     1.0.8                h2bbff1b_6
ca-certificates           2024.7.2             haa95532_0
certifi                   2024.7.4                 pypi_0    pypi
cffi                      1.16.0                   pypi_0    pypi
charset-normalizer        3.3.2                    pypi_0    pypi
click                     8.1.7                    pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
coloredlogs               15.0.1                   pypi_0    pypi
colorlog                  6.8.2                    pypi_0    pypi
contourpy                 1.2.1                    pypi_0    pypi
ctranslate2               4.3.1                    pypi_0    pypi
cuda-cccl                 12.6.37                       0    nvidia
cuda-cccl_win-64          12.6.37                       0    nvidia
cuda-cudart               11.8.89                       0    nvidia
cuda-cudart-dev           11.8.89                       0    nvidia
cuda-cupti                11.8.87                       0    nvidia
cuda-libraries            11.8.0                        0    nvidia
cuda-libraries-dev        11.8.0                        0    nvidia
cuda-nvrtc                11.8.89                       0    nvidia
cuda-nvrtc-dev            11.8.89                       0    nvidia
cuda-nvtx                 11.8.86                       0    nvidia
cuda-opencl               12.6.37                       0    nvidia
cuda-opencl-dev           12.6.37                       0    nvidia
cuda-profiler-api         12.6.37                       0    nvidia
cuda-runtime              11.8.0                        0    nvidia
cuda-version              12.6                          3    nvidia
cycler                    0.12.1                   pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
docopt                    0.6.2                    pypi_0    pypi
einops                    0.8.0                    pypi_0    pypi
faster-whisper            1.0.0                    pypi_0    pypi
filelock                  3.13.1          py310haa95532_0
flatbuffers               24.3.25                  pypi_0    pypi
fonttools                 4.53.1                   pypi_0    pypi
frozenlist                1.4.1                    pypi_0    pypi
fsspec                    2024.6.1                 pypi_0    pypi
gmpy2                     2.1.2           py310h7f96b67_0
greenlet                  3.0.3                    pypi_0    pypi
huggingface-hub           0.24.5                   pypi_0    pypi
humanfriendly             10.0                     pypi_0    pypi
hyperpyyaml               1.2.2                    pypi_0    pypi
idna                      3.7                      pypi_0    pypi
intel-openmp              2023.1.0         h59b6b97_46320
jinja2                    3.1.4           py310haa95532_0
joblib                    1.4.2                    pypi_0    pypi
julius                    0.2.7                    pypi_0    pypi
kiwisolver                1.4.5                    pypi_0    pypi
lazy-loader               0.4                      pypi_0    pypi
libcublas                 11.11.3.6                     0    nvidia
libcublas-dev             11.11.3.6                     0    nvidia
libcufft                  10.9.0.58                     0    nvidia
libcufft-dev              10.9.0.58                     0    nvidia
libcurand                 10.3.7.37                     0    nvidia
libcurand-dev             10.3.7.37                     0    nvidia
libcusolver               11.4.1.48                     0    nvidia
libcusolver-dev           11.4.1.48                     0    nvidia
libcusparse               11.7.5.86                     0    nvidia
libcusparse-dev           11.7.5.86                     0    nvidia
libffi                    3.4.4                hd77b12b_1
libnpp                    11.8.0.86                     0    nvidia
libnpp-dev                11.8.0.86                     0    nvidia
libnvjitlink              12.1.105                      0    nvidia
libnvjitlink-dev          12.1.105                      0    nvidia
libnvjpeg                 11.9.0.86                     0    nvidia
libnvjpeg-dev             11.9.0.86                     0    nvidia
librosa                   0.10.2.post1             pypi_0    pypi
libuv                     1.48.0               h827c3e9_0
lightning                 2.3.3                    pypi_0    pypi
lightning-utilities       0.11.6                   pypi_0    pypi
llvmlite                  0.43.0                   pypi_0    pypi
mako                      1.3.5                    pypi_0    pypi
markdown-it-py            3.0.0                    pypi_0    pypi
markupsafe                2.1.3           py310h2bbff1b_0
matplotlib                3.9.0                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
mkl                       2023.1.0         h6b88ed4_46358
mkl-service               2.4.0           py310h2bbff1b_1
mkl_fft                   1.3.8           py310h2bbff1b_0
mkl_random                1.2.4           py310h59b6b97_0
mpc                       1.1.0                h7edee0f_1
mpfr                      4.0.2                h62dcd97_1
mpir                      3.0.0                hec2e145_1
mpmath                    1.3.0           py310haa95532_0
msgpack                   1.0.8                    pypi_0    pypi
multidict                 6.0.5                    pypi_0    pypi
networkx                  3.3             py310haa95532_0
nltk                      3.8.1                    pypi_0    pypi
numba                     0.60.0                   pypi_0    pypi
numpy                     1.26.4          py310h055cbcc_0
numpy-base                1.26.4          py310h65a83cf_0
omegaconf                 2.3.0                    pypi_0    pypi
onnxruntime               1.18.1                   pypi_0    pypi
openssl                   3.0.14               h827c3e9_0
optuna                    3.6.1                    pypi_0    pypi
packaging                 24.1                     pypi_0    pypi
pandas                    2.2.2                    pypi_0    pypi
pillow                    10.4.0                   pypi_0    pypi
pip                       24.0            py310haa95532_0
platformdirs              4.2.2                    pypi_0    pypi
pooch                     1.8.2                    pypi_0    pypi
primepy                   1.3                      pypi_0    pypi
protobuf                  5.27.3                   pypi_0    pypi
pyannote-audio            3.1.1                    pypi_0    pypi
pyannote-core             5.0.0                    pypi_0    pypi
pyannote-database         5.1.0                    pypi_0    pypi
pyannote-metrics          3.2.1                    pypi_0    pypi
pyannote-pipeline         3.0.1                    pypi_0    pypi
pycparser                 2.22                     pypi_0    pypi
pygments                  2.18.0                   pypi_0    pypi
pyparsing                 3.1.2                    pypi_0    pypi
pyreadline3               3.4.1                    pypi_0    pypi
python                    3.10.14              he1021f5_1
python-dateutil           2.9.0.post0              pypi_0    pypi
pytorch                   2.0.0           py3.10_cuda11.8_cudnn8_0    pytorch
pytorch-cuda              11.8                 h24eeafa_5    pytorch
pytorch-lightning         2.3.3                    pypi_0    pypi
pytorch-metric-learning   2.6.0                    pypi_0    pypi
pytorch-mutex             1.0                        cuda    pytorch
pytz                      2024.1                   pypi_0    pypi
pyyaml                    6.0.1                    pypi_0    pypi
regex                     2024.7.24                pypi_0    pypi
requests                  2.32.3                   pypi_0    pypi
rich                      13.7.1                   pypi_0    pypi
ruamel-yaml               0.18.6                   pypi_0    pypi
ruamel-yaml-clib          0.2.8                    pypi_0    pypi
safetensors               0.4.3                    pypi_0    pypi
scikit-learn              1.5.1                    pypi_0    pypi
scipy                     1.14.0                   pypi_0    pypi
semver                    3.0.2                    pypi_0    pypi
sentencepiece             0.2.0                    pypi_0    pypi
setuptools                72.1.0                   pypi_0    pypi
shellingham               1.5.4                    pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
sortedcontainers          2.4.0                    pypi_0    pypi
soundfile                 0.12.1                   pypi_0    pypi
soxr                      0.4.0                    pypi_0    pypi
speechbrain               1.0.0                    pypi_0    pypi
sqlalchemy                2.0.31                   pypi_0    pypi
sqlite                    3.45.3               h2bbff1b_0
sympy                     1.12            py310haa95532_0
tabulate                  0.9.0                    pypi_0    pypi
tbb                       2021.8.0             h59b6b97_0
tensorboardx              2.6.2.2                  pypi_0    pypi
threadpoolctl             3.5.0                    pypi_0    pypi
tk                        8.6.14               h0416ee5_0
tokenizers                0.15.2                   pypi_0    pypi
torch-audiomentations     0.11.1                   pypi_0    pypi
torch-pitch-shift         1.2.4                    pypi_0    pypi
torchaudio                2.0.0                    pypi_0    pypi
torchmetrics              1.4.1                    pypi_0    pypi
tqdm                      4.66.5                   pypi_0    pypi
transformers              4.39.3                   pypi_0    pypi
typer                     0.12.3                   pypi_0    pypi
typing_extensions         4.11.0          py310haa95532_0
tzdata                    2024.1                   pypi_0    pypi
urllib3                   2.2.2                    pypi_0    pypi
vc                        14.2                 h2eaa2aa_4
vs2015_runtime            14.29.30133          h43f2093_4
wheel                     0.43.0          py310haa95532_0
whisperx                  3.1.1                    pypi_0    pypi
xz                        5.4.6                h8cc25b3_1
yarl                      1.9.4                    pypi_0    pypi
zlib                      1.2.13               h8cc25b3_
```

### Steps followed

![image](https://github.com/user-attachments/assets/2e863bc8-18b2-47ed-9a11-757dd2eda269)

**Comment by Marek2k17** [comment]
If you read the setup i tells you the installation needs cuBLAS 11.x and cuDNN 8.x
cuBLAS is part of the CUDA Toolkit, for cuDNN you need to visit https://developer.nvidia.com/rdp/cudnn-archive
Running the Setup for CUDA Toolkit and manually installing cuDNN should work

**Comment by GlitCher50** [comment]
Yes it worked, thanks @Marek2k17 @emergencyreports
