### ISSUE TITLE
Python 3.7 compatibility ?

### ISSUE THREAD

**Issue by canie30** [m-bain/whisperX#92]
Hi,
I'm running under 3.7 for compatibility issue with my project, and whiperX seems to need 3.9. Whisper although was tested and developped with 3.9 is full compatible with 3.7, is there by any mean a solution to run WhisperX with 3.7 ?

I think it's a compatibility issue, cause i got this error when running in 3.7 : 

whisperx sample01.wav 

```
Traceback (most recent call last):
  File "/usr/local/bin/whisperx", line 5, in <module>
    from whisperx.transcribe import cli
  File "/home/vscode/.local/lib/python3.7/site-packages/whisperx/__init__.py", line 13, in <module>
    from .model import Whisper, ModelDimensions
  File "/home/vscode/.local/lib/python3.7/site-packages/whisperx/model.py", line 11, in <module>
    from .transcribe import transcribe as transcribe_function
  File "/home/vscode/.local/lib/python3.7/site-packages/whisperx/transcribe.py", line 10, in <module>
    from .alignment import load_align_model, align, get_trellis, backtrack, merge_repeats, merge_words
  File "/home/vscode/.local/lib/python3.7/site-packages/whisperx/alignment.py", line 248
    seg_lens_cumsum = [v := v + n for n in seg_lens]
```

**Comment by rbychn** [comment]
you can try anaconda env and try creating a new env with that python version

**Comment by canie30** [comment]
> you can try anaconda env and try creating a new env with that python version

Not sure i can, i have to arts of my same script that need different versions of python, and i'm not sure conda can do that, if i'm mistaken if you have a link to a sample code with python version switch inside a same script that'd be great ;-)
